# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tools/Xilinx/Vitis/2020.1/workspace/test_fast/Hardware/krnl_cornertracker.build/link/vivado/vpl/prj/prj.srcs/sources_1/bd/zcu104_base/ip/zcu104_base_auto_us_df_2/zcu104_base_auto_us_df_2.xci
# IP: The module: 'zcu104_base_auto_us_df_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tools/Xilinx/Vitis/2020.1/workspace/test_fast/Hardware/krnl_cornertracker.build/link/vivado/vpl/prj/prj.srcs/sources_1/bd/zcu104_base/ip/zcu104_base_auto_us_df_2/zcu104_base_auto_us_df_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu104_base_auto_us_df_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /tools/Xilinx/Vitis/2020.1/workspace/test_fast/Hardware/krnl_cornertracker.build/link/vivado/vpl/prj/prj.srcs/sources_1/bd/zcu104_base/ip/zcu104_base_auto_us_df_2/zcu104_base_auto_us_df_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu104_base_auto_us_df_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /tools/Xilinx/Vitis/2020.1/workspace/test_fast/Hardware/krnl_cornertracker.build/link/vivado/vpl/prj/prj.srcs/sources_1/bd/zcu104_base/ip/zcu104_base_auto_us_df_2/zcu104_base_auto_us_df_2.xci
# IP: The module: 'zcu104_base_auto_us_df_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tools/Xilinx/Vitis/2020.1/workspace/test_fast/Hardware/krnl_cornertracker.build/link/vivado/vpl/prj/prj.srcs/sources_1/bd/zcu104_base/ip/zcu104_base_auto_us_df_2/zcu104_base_auto_us_df_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu104_base_auto_us_df_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /tools/Xilinx/Vitis/2020.1/workspace/test_fast/Hardware/krnl_cornertracker.build/link/vivado/vpl/prj/prj.srcs/sources_1/bd/zcu104_base/ip/zcu104_base_auto_us_df_2/zcu104_base_auto_us_df_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu104_base_auto_us_df_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
