# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tools/Xilinx/Vitis/2020.1/workspace/test_fast/Hardware/krnl_cornertracker.build/link/vivado/vpl/prj/prj.srcs/sources_1/bd/zcu104_base/ip/zcu104_base_pyr_dense_optical_flow_accel_1_0/zcu104_base_pyr_dense_optical_flow_accel_1_0.xci
# IP: The module: 'zcu104_base_pyr_dense_optical_flow_accel_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tools/Xilinx/Vitis/2020.1/workspace/test_fast/Hardware/krnl_cornertracker.build/link/vivado/vpl/prj/prj.srcs/sources_1/bd/zcu104_base/ip/zcu104_base_pyr_dense_optical_flow_accel_1_0/constraints/pyr_dense_optical_flow_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu104_base_pyr_dense_optical_flow_accel_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /tools/Xilinx/Vitis/2020.1/workspace/test_fast/Hardware/krnl_cornertracker.build/link/vivado/vpl/prj/prj.srcs/sources_1/bd/zcu104_base/ip/zcu104_base_pyr_dense_optical_flow_accel_1_0/zcu104_base_pyr_dense_optical_flow_accel_1_0.xci
# IP: The module: 'zcu104_base_pyr_dense_optical_flow_accel_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tools/Xilinx/Vitis/2020.1/workspace/test_fast/Hardware/krnl_cornertracker.build/link/vivado/vpl/prj/prj.srcs/sources_1/bd/zcu104_base/ip/zcu104_base_pyr_dense_optical_flow_accel_1_0/constraints/pyr_dense_optical_flow_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zcu104_base_pyr_dense_optical_flow_accel_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
