// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cornerTracker_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_s (
        in_harris_mat_419_dout,
        in_harris_mat_419_empty_n,
        in_harris_mat_419_read,
        out_harris_mat_420_din,
        out_harris_mat_420_full_n,
        out_harris_mat_420_write,
        p_read,
        p_read1,
        img_height,
        img_width,
        p_threshold,
        ap_clk,
        ap_rst,
        p_read_ap_vld,
        p_read1_ap_vld,
        img_height_ap_vld,
        img_width_ap_vld,
        p_threshold_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [7:0] in_harris_mat_419_dout;
input   in_harris_mat_419_empty_n;
output   in_harris_mat_419_read;
output  [7:0] out_harris_mat_420_din;
input   out_harris_mat_420_full_n;
output   out_harris_mat_420_write;
input  [10:0] p_read;
input  [10:0] p_read1;
input  [10:0] img_height;
input  [10:0] img_width;
input  [15:0] p_threshold;
input   ap_clk;
input   ap_rst;
input   p_read_ap_vld;
input   p_read1_ap_vld;
input   img_height_ap_vld;
input   img_width_ap_vld;
input   p_threshold_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_start;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_start_full_n;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_done;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_continue;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_idle;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_start_out;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_start_write;
wire   [10:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_src_mat_1_out_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_src_mat_1_out_write;
wire   [10:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_src_mat_2_out_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_src_mat_2_out_write;
wire   [10:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out_write;
wire   [10:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out1_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out1_write;
wire   [10:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out2_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out2_write;
wire   [10:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out_write;
wire   [10:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out3_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out3_write;
wire   [10:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out4_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out4_write;
wire   [15:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_threshold_out_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_threshold_out_write;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_start;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_full_n;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_idle;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_out;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_height_read;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_width_read;
wire   [10:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradx_2_rows_out_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradx_2_rows_out_write;
wire   [10:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradx_2_cols_out_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradx_2_cols_out_write;
wire   [10:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_grady_2_rows_out_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_grady_2_rows_out_write;
wire   [10:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_grady_2_cols_out_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_grady_2_cols_out_write;
wire   [10:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradxy_rows_out_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradxy_rows_out_write;
wire   [10:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradxy_cols_out_din;
wire    xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradxy_cols_out_write;
wire    Sobel_0_3_0_2_1080_1920_1_false_U0_ap_start;
wire    Sobel_0_3_0_2_1080_1920_1_false_U0_ap_done;
wire    Sobel_0_3_0_2_1080_1920_1_false_U0_ap_continue;
wire    Sobel_0_3_0_2_1080_1920_1_false_U0_ap_idle;
wire    Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready;
wire    Sobel_0_3_0_2_1080_1920_1_false_U0_in_harris_mat_419_read;
wire   [15:0] Sobel_0_3_0_2_1080_1920_1_false_U0_gradx_mat_49_din;
wire    Sobel_0_3_0_2_1080_1920_1_false_U0_gradx_mat_49_write;
wire   [15:0] Sobel_0_3_0_2_1080_1920_1_false_U0_grady_mat_410_din;
wire    Sobel_0_3_0_2_1080_1920_1_false_U0_grady_mat_410_write;
wire    Sobel_0_3_0_2_1080_1920_1_false_U0_p_src_mat_1_read;
wire    Sobel_0_3_0_2_1080_1920_1_false_U0_p_src_mat_2_read;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_ap_start;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_start_full_n;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_ap_done;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_ap_continue;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_ap_idle;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_ap_ready;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_start_out;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_start_write;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx_mat_49_read;
wire   [15:0] xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx1_mat_411_din;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx1_mat_411_write;
wire   [15:0] xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx2_mat_413_din;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx2_mat_413_write;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_read;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_read;
wire   [10:0] xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_out_din;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_out_write;
wire   [10:0] xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_out1_din;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_out1_write;
wire   [10:0] xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_out_din;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_out_write;
wire   [10:0] xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_out2_din;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_out2_write;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_U0_ap_start;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_U0_ap_done;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_U0_ap_continue;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_U0_ap_idle;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_U0_ap_ready;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_U0_start_out;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_U0_start_write;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx_mat_49_read;
wire   [15:0] xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx1_mat_411_din;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx1_mat_411_write;
wire   [15:0] xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx2_mat_413_din;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx2_mat_413_write;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_height_read;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_width_read;
wire   [10:0] xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_height_out_din;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_height_out_write;
wire   [10:0] xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_width_out_din;
wire    xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_width_out_write;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_ap_start;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_ap_done;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_ap_continue;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_ap_idle;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_ap_ready;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_start_out;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_start_write;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_gradx1_mat_411_read;
wire   [15:0] xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_gradx_2_41_din;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_gradx_2_41_write;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_height_read;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_width_read;
wire   [10:0] xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_height_out_din;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_height_out_write;
wire   [10:0] xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_width_out_din;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_width_out_write;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_start;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_done;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_continue;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_idle;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_ready;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradx1_mat_411_read;
wire   [15:0] xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradx_2_41_din;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradx_2_41_write;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_img_height_read;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_img_width_read;
wire    xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_start;
wire    xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_done;
wire    xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_continue;
wire    xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_idle;
wire    xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_ready;
wire    xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradx2_mat_413_read;
wire    xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_grady2_mat_414_read;
wire   [15:0] xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradxy_43_din;
wire    xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradxy_43_write;
wire    xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_img_height_read;
wire    xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_img_width_read;
wire    boxFilter_0_3_2_1080_1920_1_false_26_U0_ap_start;
wire    boxFilter_0_3_2_1080_1920_1_false_26_U0_ap_done;
wire    boxFilter_0_3_2_1080_1920_1_false_26_U0_ap_continue;
wire    boxFilter_0_3_2_1080_1920_1_false_26_U0_ap_idle;
wire    boxFilter_0_3_2_1080_1920_1_false_26_U0_ap_ready;
wire    boxFilter_0_3_2_1080_1920_1_false_26_U0_gradx_2_41_read;
wire   [15:0] boxFilter_0_3_2_1080_1920_1_false_26_U0_gradx2g_44_din;
wire    boxFilter_0_3_2_1080_1920_1_false_26_U0_gradx2g_44_write;
wire    boxFilter_0_3_2_1080_1920_1_false_26_U0_p_src_mat_1_read;
wire    boxFilter_0_3_2_1080_1920_1_false_26_U0_p_src_mat_2_read;
wire    boxFilter_0_3_2_1080_1920_1_false_27_U0_ap_start;
wire    boxFilter_0_3_2_1080_1920_1_false_27_U0_ap_done;
wire    boxFilter_0_3_2_1080_1920_1_false_27_U0_ap_continue;
wire    boxFilter_0_3_2_1080_1920_1_false_27_U0_ap_idle;
wire    boxFilter_0_3_2_1080_1920_1_false_27_U0_ap_ready;
wire    boxFilter_0_3_2_1080_1920_1_false_27_U0_gradx_2_41_read;
wire   [15:0] boxFilter_0_3_2_1080_1920_1_false_27_U0_gradx2g_44_din;
wire    boxFilter_0_3_2_1080_1920_1_false_27_U0_gradx2g_44_write;
wire    boxFilter_0_3_2_1080_1920_1_false_27_U0_p_src_mat_1_read;
wire    boxFilter_0_3_2_1080_1920_1_false_27_U0_p_src_mat_2_read;
wire    boxFilter_0_3_2_1080_1920_1_false_U0_ap_start;
wire    boxFilter_0_3_2_1080_1920_1_false_U0_ap_done;
wire    boxFilter_0_3_2_1080_1920_1_false_U0_ap_continue;
wire    boxFilter_0_3_2_1080_1920_1_false_U0_ap_idle;
wire    boxFilter_0_3_2_1080_1920_1_false_U0_ap_ready;
wire    boxFilter_0_3_2_1080_1920_1_false_U0_gradx_2_41_read;
wire   [15:0] boxFilter_0_3_2_1080_1920_1_false_U0_gradx2g_44_din;
wire    boxFilter_0_3_2_1080_1920_1_false_U0_gradx2g_44_write;
wire    boxFilter_0_3_2_1080_1920_1_false_U0_p_src_mat_1_read;
wire    boxFilter_0_3_2_1080_1920_1_false_U0_p_src_mat_2_read;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_ap_start;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_ap_done;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_ap_continue;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_ap_idle;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_ap_ready;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_gradx2g_44_read;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_grady2g_45_read;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_gradxyg_46_read;
wire   [31:0] xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_score_47_din;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_score_47_write;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_height_read;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_width_read;
wire   [10:0] xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_height_out_din;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_height_out_write;
wire   [10:0] xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_width_out_din;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_width_out_write;
wire    xFThreshold_5_1080_1920_5_1_12_1920_U0_ap_start;
wire    xFThreshold_5_1080_1920_5_1_12_1920_U0_ap_done;
wire    xFThreshold_5_1080_1920_5_1_12_1920_U0_ap_continue;
wire    xFThreshold_5_1080_1920_5_1_12_1920_U0_ap_idle;
wire    xFThreshold_5_1080_1920_5_1_12_1920_U0_ap_ready;
wire    xFThreshold_5_1080_1920_5_1_12_1920_U0_start_out;
wire    xFThreshold_5_1080_1920_5_1_12_1920_U0_start_write;
wire    xFThreshold_5_1080_1920_5_1_12_1920_U0_score_47_read;
wire   [31:0] xFThreshold_5_1080_1920_5_1_12_1920_U0_thresh_48_din;
wire    xFThreshold_5_1080_1920_5_1_12_1920_U0_thresh_48_write;
wire    xFThreshold_5_1080_1920_5_1_12_1920_U0_threshold_read;
wire    xFThreshold_5_1080_1920_5_1_12_1920_U0_img_height_read;
wire    xFThreshold_5_1080_1920_5_1_12_1920_U0_img_width_read;
wire   [10:0] xFThreshold_5_1080_1920_5_1_12_1920_U0_img_height_out_din;
wire    xFThreshold_5_1080_1920_5_1_12_1920_U0_img_height_out_write;
wire   [10:0] xFThreshold_5_1080_1920_5_1_12_1920_U0_img_width_out_din;
wire    xFThreshold_5_1080_1920_5_1_12_1920_U0_img_width_out_write;
wire    xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_start;
wire    xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_done;
wire    xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_continue;
wire    xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_idle;
wire    xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_ready;
wire    xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_thresh_48_read;
wire   [7:0] xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_out_harris_mat_420_din;
wire    xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_out_harris_mat_420_write;
wire    xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_img_height_read;
wire    xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_img_width_read;
wire    ap_sync_continue;
wire    p_src_mat_1_c_full_n;
wire   [10:0] p_src_mat_1_c_dout;
wire    p_src_mat_1_c_empty_n;
wire    p_src_mat_2_c_full_n;
wire   [10:0] p_src_mat_2_c_dout;
wire    p_src_mat_2_c_empty_n;
wire    img_height_c_full_n;
wire   [10:0] img_height_c_dout;
wire    img_height_c_empty_n;
wire    img_height_c27_full_n;
wire   [10:0] img_height_c27_dout;
wire    img_height_c27_empty_n;
wire    img_height_c28_full_n;
wire   [10:0] img_height_c28_dout;
wire    img_height_c28_empty_n;
wire    img_width_c_full_n;
wire   [10:0] img_width_c_dout;
wire    img_width_c_empty_n;
wire    img_width_c29_full_n;
wire   [10:0] img_width_c29_dout;
wire    img_width_c29_empty_n;
wire    img_width_c30_full_n;
wire   [10:0] img_width_c30_dout;
wire    img_width_c30_empty_n;
wire    p_threshold_c_full_n;
wire   [15:0] p_threshold_c_dout;
wire    p_threshold_c_empty_n;
wire    gradx_2_rows_c_full_n;
wire   [10:0] gradx_2_rows_c_dout;
wire    gradx_2_rows_c_empty_n;
wire    gradx_2_cols_c_full_n;
wire   [10:0] gradx_2_cols_c_dout;
wire    gradx_2_cols_c_empty_n;
wire    grady_2_rows_c_full_n;
wire   [10:0] grady_2_rows_c_dout;
wire    grady_2_rows_c_empty_n;
wire    grady_2_cols_c_full_n;
wire   [10:0] grady_2_cols_c_dout;
wire    grady_2_cols_c_empty_n;
wire    gradxy_rows_c_full_n;
wire   [10:0] gradxy_rows_c_dout;
wire    gradxy_rows_c_empty_n;
wire    gradxy_cols_c_full_n;
wire   [10:0] gradxy_cols_c_dout;
wire    gradxy_cols_c_empty_n;
wire    gradx_mat_data_full_n;
wire   [15:0] gradx_mat_data_dout;
wire    gradx_mat_data_empty_n;
wire    grady_mat_data_full_n;
wire   [15:0] grady_mat_data_dout;
wire    grady_mat_data_empty_n;
wire    gradx1_mat_data_full_n;
wire   [15:0] gradx1_mat_data_dout;
wire    gradx1_mat_data_empty_n;
wire    gradx2_mat_data_full_n;
wire   [15:0] gradx2_mat_data_dout;
wire    gradx2_mat_data_empty_n;
wire    img_height_c31_full_n;
wire   [10:0] img_height_c31_dout;
wire    img_height_c31_empty_n;
wire    img_height_c32_full_n;
wire   [10:0] img_height_c32_dout;
wire    img_height_c32_empty_n;
wire    img_width_c33_full_n;
wire   [10:0] img_width_c33_dout;
wire    img_width_c33_empty_n;
wire    img_width_c34_full_n;
wire   [10:0] img_width_c34_dout;
wire    img_width_c34_empty_n;
wire    grady1_mat_data_full_n;
wire   [15:0] grady1_mat_data_dout;
wire    grady1_mat_data_empty_n;
wire    grady2_mat_data_full_n;
wire   [15:0] grady2_mat_data_dout;
wire    grady2_mat_data_empty_n;
wire    img_height_c35_full_n;
wire   [10:0] img_height_c35_dout;
wire    img_height_c35_empty_n;
wire    img_width_c36_full_n;
wire   [10:0] img_width_c36_dout;
wire    img_width_c36_empty_n;
wire    gradx_2_data_full_n;
wire   [15:0] gradx_2_data_dout;
wire    gradx_2_data_empty_n;
wire    img_height_c37_full_n;
wire   [10:0] img_height_c37_dout;
wire    img_height_c37_empty_n;
wire    img_width_c38_full_n;
wire   [10:0] img_width_c38_dout;
wire    img_width_c38_empty_n;
wire    grady_2_data_full_n;
wire   [15:0] grady_2_data_dout;
wire    grady_2_data_empty_n;
wire    gradxy_data_full_n;
wire   [15:0] gradxy_data_dout;
wire    gradxy_data_empty_n;
wire    gradx2g_data_full_n;
wire   [15:0] gradx2g_data_dout;
wire    gradx2g_data_empty_n;
wire    grady2g_data_full_n;
wire   [15:0] grady2g_data_dout;
wire    grady2g_data_empty_n;
wire    gradxyg_data_full_n;
wire   [15:0] gradxyg_data_dout;
wire    gradxyg_data_empty_n;
wire    score_data_full_n;
wire   [31:0] score_data_dout;
wire    score_data_empty_n;
wire    img_height_c39_full_n;
wire   [10:0] img_height_c39_dout;
wire    img_height_c39_empty_n;
wire    img_width_c40_full_n;
wire   [10:0] img_width_c40_dout;
wire    img_width_c40_empty_n;
wire    thresh_data_full_n;
wire   [31:0] thresh_data_dout;
wire    thresh_data_empty_n;
wire    img_height_c41_full_n;
wire   [10:0] img_height_c41_dout;
wire    img_height_c41_empty_n;
wire    img_width_c42_full_n;
wire   [10:0] img_width_c42_dout;
wire    img_width_c42_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready;
wire    ap_sync_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready;
reg   [1:0] xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready_count;
reg    ap_sync_reg_Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready;
wire    ap_sync_Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready;
reg   [1:0] Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready_count;
wire   [0:0] start_for_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_din;
wire    start_for_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_full_n;
wire   [0:0] start_for_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_dout;
wire    start_for_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_empty_n;
wire   [0:0] start_for_xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_din;
wire    start_for_xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_full_n;
wire   [0:0] start_for_xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_dout;
wire    start_for_xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_empty_n;
wire   [0:0] start_for_xFDuplicate_2_1080_1920_3_1_5_1920_U0_din;
wire    start_for_xFDuplicate_2_1080_1920_3_1_5_1920_U0_full_n;
wire   [0:0] start_for_xFDuplicate_2_1080_1920_3_1_5_1920_U0_dout;
wire    start_for_xFDuplicate_2_1080_1920_3_1_5_1920_U0_empty_n;
wire   [0:0] start_for_xFThreshold_5_1080_1920_5_1_12_1920_U0_din;
wire    start_for_xFThreshold_5_1080_1920_5_1_12_1920_U0_full_n;
wire   [0:0] start_for_xFThreshold_5_1080_1920_5_1_12_1920_U0_dout;
wire    start_for_xFThreshold_5_1080_1920_5_1_12_1920_U0_empty_n;
wire   [0:0] start_for_boxFilter_0_3_2_1080_1920_1_false_26_U0_din;
wire    start_for_boxFilter_0_3_2_1080_1920_1_false_26_U0_full_n;
wire   [0:0] start_for_boxFilter_0_3_2_1080_1920_1_false_26_U0_dout;
wire    start_for_boxFilter_0_3_2_1080_1920_1_false_26_U0_empty_n;
wire   [0:0] start_for_boxFilter_0_3_2_1080_1920_1_false_27_U0_din;
wire    start_for_boxFilter_0_3_2_1080_1920_1_false_27_U0_full_n;
wire   [0:0] start_for_boxFilter_0_3_2_1080_1920_1_false_27_U0_dout;
wire    start_for_boxFilter_0_3_2_1080_1920_1_false_27_U0_empty_n;
wire   [0:0] start_for_boxFilter_0_3_2_1080_1920_1_false_U0_din;
wire    start_for_boxFilter_0_3_2_1080_1920_1_false_U0_full_n;
wire   [0:0] start_for_boxFilter_0_3_2_1080_1920_1_false_U0_dout;
wire    start_for_boxFilter_0_3_2_1080_1920_1_false_U0_empty_n;
wire    Sobel_0_3_0_2_1080_1920_1_false_U0_start_full_n;
wire    Sobel_0_3_0_2_1080_1920_1_false_U0_start_write;
wire   [0:0] start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_din;
wire    start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_full_n;
wire   [0:0] start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_dout;
wire    start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_empty_n;
wire   [0:0] start_for_xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_din;
wire    start_for_xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_full_n;
wire   [0:0] start_for_xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_dout;
wire    start_for_xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_empty_n;
wire   [0:0] start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_din;
wire    start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_full_n;
wire   [0:0] start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_dout;
wire    start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_empty_n;
wire   [0:0] start_for_xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_din;
wire    start_for_xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_full_n;
wire   [0:0] start_for_xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_dout;
wire    start_for_xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_empty_n;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_start_full_n;
wire    xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_start_write;
wire    xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_start_full_n;
wire    xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_start_write;
wire    boxFilter_0_3_2_1080_1920_1_false_26_U0_start_full_n;
wire    boxFilter_0_3_2_1080_1920_1_false_26_U0_start_write;
wire    boxFilter_0_3_2_1080_1920_1_false_27_U0_start_full_n;
wire    boxFilter_0_3_2_1080_1920_1_false_27_U0_start_write;
wire    boxFilter_0_3_2_1080_1920_1_false_U0_start_full_n;
wire    boxFilter_0_3_2_1080_1920_1_false_U0_start_write;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_start_full_n;
wire    xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_start_write;
wire   [0:0] start_for_xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_din;
wire    start_for_xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_full_n;
wire   [0:0] start_for_xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_dout;
wire    start_for_xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_empty_n;
wire    xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_start_full_n;
wire    xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready = 1'b0;
#0 xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready = 1'b0;
#0 Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready_count = 2'd0;
end

cornerTracker_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50 xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_start),
    .start_full_n(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_start_full_n),
    .ap_done(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_done),
    .ap_continue(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_continue),
    .ap_idle(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_idle),
    .ap_ready(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready),
    .start_out(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_start_out),
    .start_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_start_write),
    .p_read(p_read),
    .p_read1(p_read1),
    .img_height(img_height),
    .img_width(img_width),
    .p_threshold(p_threshold),
    .p_src_mat_1_out_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_src_mat_1_out_din),
    .p_src_mat_1_out_full_n(p_src_mat_1_c_full_n),
    .p_src_mat_1_out_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_src_mat_1_out_write),
    .p_src_mat_2_out_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_src_mat_2_out_din),
    .p_src_mat_2_out_full_n(p_src_mat_2_c_full_n),
    .p_src_mat_2_out_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_src_mat_2_out_write),
    .img_height_out_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out_din),
    .img_height_out_full_n(img_height_c_full_n),
    .img_height_out_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out_write),
    .img_height_out1_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out1_din),
    .img_height_out1_full_n(img_height_c27_full_n),
    .img_height_out1_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out1_write),
    .img_height_out2_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out2_din),
    .img_height_out2_full_n(img_height_c28_full_n),
    .img_height_out2_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out2_write),
    .img_width_out_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out_din),
    .img_width_out_full_n(img_width_c_full_n),
    .img_width_out_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out_write),
    .img_width_out3_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out3_din),
    .img_width_out3_full_n(img_width_c29_full_n),
    .img_width_out3_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out3_write),
    .img_width_out4_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out4_din),
    .img_width_out4_full_n(img_width_c30_full_n),
    .img_width_out4_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out4_write),
    .p_threshold_out_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_threshold_out_din),
    .p_threshold_out_full_n(p_threshold_c_full_n),
    .p_threshold_out_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_threshold_out_write)
);

cornerTracker_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_start),
    .start_full_n(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_full_n),
    .ap_done(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done),
    .ap_continue(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue),
    .ap_idle(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_idle),
    .ap_ready(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready),
    .start_out(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_out),
    .start_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write),
    .img_height_dout(img_height_c_dout),
    .img_height_empty_n(img_height_c_empty_n),
    .img_height_read(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_height_read),
    .img_width_dout(img_width_c_dout),
    .img_width_empty_n(img_width_c_empty_n),
    .img_width_read(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_width_read),
    .gradx_2_rows_out_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradx_2_rows_out_din),
    .gradx_2_rows_out_full_n(gradx_2_rows_c_full_n),
    .gradx_2_rows_out_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradx_2_rows_out_write),
    .gradx_2_cols_out_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradx_2_cols_out_din),
    .gradx_2_cols_out_full_n(gradx_2_cols_c_full_n),
    .gradx_2_cols_out_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradx_2_cols_out_write),
    .grady_2_rows_out_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_grady_2_rows_out_din),
    .grady_2_rows_out_full_n(grady_2_rows_c_full_n),
    .grady_2_rows_out_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_grady_2_rows_out_write),
    .grady_2_cols_out_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_grady_2_cols_out_din),
    .grady_2_cols_out_full_n(grady_2_cols_c_full_n),
    .grady_2_cols_out_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_grady_2_cols_out_write),
    .gradxy_rows_out_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradxy_rows_out_din),
    .gradxy_rows_out_full_n(gradxy_rows_c_full_n),
    .gradxy_rows_out_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradxy_rows_out_write),
    .gradxy_cols_out_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradxy_cols_out_din),
    .gradxy_cols_out_full_n(gradxy_cols_c_full_n),
    .gradxy_cols_out_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradxy_cols_out_write)
);

cornerTracker_Sobel_0_3_0_2_1080_1920_1_false_s Sobel_0_3_0_2_1080_1920_1_false_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Sobel_0_3_0_2_1080_1920_1_false_U0_ap_start),
    .ap_done(Sobel_0_3_0_2_1080_1920_1_false_U0_ap_done),
    .ap_continue(Sobel_0_3_0_2_1080_1920_1_false_U0_ap_continue),
    .ap_idle(Sobel_0_3_0_2_1080_1920_1_false_U0_ap_idle),
    .ap_ready(Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready),
    .in_harris_mat_419_dout(in_harris_mat_419_dout),
    .in_harris_mat_419_empty_n(in_harris_mat_419_empty_n),
    .in_harris_mat_419_read(Sobel_0_3_0_2_1080_1920_1_false_U0_in_harris_mat_419_read),
    .gradx_mat_49_din(Sobel_0_3_0_2_1080_1920_1_false_U0_gradx_mat_49_din),
    .gradx_mat_49_full_n(gradx_mat_data_full_n),
    .gradx_mat_49_write(Sobel_0_3_0_2_1080_1920_1_false_U0_gradx_mat_49_write),
    .grady_mat_410_din(Sobel_0_3_0_2_1080_1920_1_false_U0_grady_mat_410_din),
    .grady_mat_410_full_n(grady_mat_data_full_n),
    .grady_mat_410_write(Sobel_0_3_0_2_1080_1920_1_false_U0_grady_mat_410_write),
    .p_src_mat_1_dout(p_src_mat_1_c_dout),
    .p_src_mat_1_empty_n(p_src_mat_1_c_empty_n),
    .p_src_mat_1_read(Sobel_0_3_0_2_1080_1920_1_false_U0_p_src_mat_1_read),
    .p_src_mat_2_dout(p_src_mat_2_c_dout),
    .p_src_mat_2_empty_n(p_src_mat_2_c_empty_n),
    .p_src_mat_2_read(Sobel_0_3_0_2_1080_1920_1_false_U0_p_src_mat_2_read)
);

cornerTracker_xFDuplicate_2_1080_1920_3_1_5_1920_24 xFDuplicate_2_1080_1920_3_1_5_1920_24_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_ap_start),
    .start_full_n(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_start_full_n),
    .ap_done(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_ap_done),
    .ap_continue(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_ap_continue),
    .ap_idle(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_ap_idle),
    .ap_ready(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_ap_ready),
    .start_out(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_start_out),
    .start_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_start_write),
    .gradx_mat_49_dout(gradx_mat_data_dout),
    .gradx_mat_49_empty_n(gradx_mat_data_empty_n),
    .gradx_mat_49_read(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx_mat_49_read),
    .gradx1_mat_411_din(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx1_mat_411_din),
    .gradx1_mat_411_full_n(gradx1_mat_data_full_n),
    .gradx1_mat_411_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx1_mat_411_write),
    .gradx2_mat_413_din(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx2_mat_413_din),
    .gradx2_mat_413_full_n(gradx2_mat_data_full_n),
    .gradx2_mat_413_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx2_mat_413_write),
    .img_height_dout(img_height_c27_dout),
    .img_height_empty_n(img_height_c27_empty_n),
    .img_height_read(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_read),
    .img_width_dout(img_width_c29_dout),
    .img_width_empty_n(img_width_c29_empty_n),
    .img_width_read(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_read),
    .img_height_out_din(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_out_din),
    .img_height_out_full_n(img_height_c31_full_n),
    .img_height_out_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_out_write),
    .img_height_out1_din(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_out1_din),
    .img_height_out1_full_n(img_height_c32_full_n),
    .img_height_out1_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_out1_write),
    .img_width_out_din(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_out_din),
    .img_width_out_full_n(img_width_c33_full_n),
    .img_width_out_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_out_write),
    .img_width_out2_din(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_out2_din),
    .img_width_out2_full_n(img_width_c34_full_n),
    .img_width_out2_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_out2_write)
);

cornerTracker_xFDuplicate_2_1080_1920_3_1_5_1920_s xFDuplicate_2_1080_1920_3_1_5_1920_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFDuplicate_2_1080_1920_3_1_5_1920_U0_ap_start),
    .start_full_n(start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_full_n),
    .ap_done(xFDuplicate_2_1080_1920_3_1_5_1920_U0_ap_done),
    .ap_continue(xFDuplicate_2_1080_1920_3_1_5_1920_U0_ap_continue),
    .ap_idle(xFDuplicate_2_1080_1920_3_1_5_1920_U0_ap_idle),
    .ap_ready(xFDuplicate_2_1080_1920_3_1_5_1920_U0_ap_ready),
    .start_out(xFDuplicate_2_1080_1920_3_1_5_1920_U0_start_out),
    .start_write(xFDuplicate_2_1080_1920_3_1_5_1920_U0_start_write),
    .gradx_mat_49_dout(grady_mat_data_dout),
    .gradx_mat_49_empty_n(grady_mat_data_empty_n),
    .gradx_mat_49_read(xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx_mat_49_read),
    .gradx1_mat_411_din(xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx1_mat_411_din),
    .gradx1_mat_411_full_n(grady1_mat_data_full_n),
    .gradx1_mat_411_write(xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx1_mat_411_write),
    .gradx2_mat_413_din(xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx2_mat_413_din),
    .gradx2_mat_413_full_n(grady2_mat_data_full_n),
    .gradx2_mat_413_write(xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx2_mat_413_write),
    .img_height_dout(img_height_c28_dout),
    .img_height_empty_n(img_height_c28_empty_n),
    .img_height_read(xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_height_read),
    .img_width_dout(img_width_c30_dout),
    .img_width_empty_n(img_width_c30_empty_n),
    .img_width_read(xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_width_read),
    .img_height_out_din(xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_height_out_din),
    .img_height_out_full_n(img_height_c35_full_n),
    .img_height_out_write(xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_height_out_write),
    .img_width_out_din(xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_width_out_din),
    .img_width_out_full_n(img_width_c36_full_n),
    .img_width_out_write(xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_width_out_write)
);

cornerTracker_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25 xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_ap_start),
    .start_full_n(start_for_xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_full_n),
    .ap_done(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_ap_done),
    .ap_continue(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_ap_continue),
    .ap_idle(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_ap_idle),
    .ap_ready(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_ap_ready),
    .start_out(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_start_out),
    .start_write(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_start_write),
    .gradx1_mat_411_dout(gradx1_mat_data_dout),
    .gradx1_mat_411_empty_n(gradx1_mat_data_empty_n),
    .gradx1_mat_411_read(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_gradx1_mat_411_read),
    .gradx_2_41_din(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_gradx_2_41_din),
    .gradx_2_41_full_n(gradx_2_data_full_n),
    .gradx_2_41_write(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_gradx_2_41_write),
    .img_height_dout(img_height_c31_dout),
    .img_height_empty_n(img_height_c31_empty_n),
    .img_height_read(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_height_read),
    .img_width_dout(img_width_c33_dout),
    .img_width_empty_n(img_width_c33_empty_n),
    .img_width_read(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_width_read),
    .img_height_out_din(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_height_out_din),
    .img_height_out_full_n(img_height_c37_full_n),
    .img_height_out_write(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_height_out_write),
    .img_width_out_din(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_width_out_din),
    .img_width_out_full_n(img_width_c38_full_n),
    .img_width_out_write(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_width_out_write)
);

cornerTracker_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_s xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_start),
    .ap_done(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_done),
    .ap_continue(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_continue),
    .ap_idle(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_idle),
    .ap_ready(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_ready),
    .gradx1_mat_411_dout(grady1_mat_data_dout),
    .gradx1_mat_411_empty_n(grady1_mat_data_empty_n),
    .gradx1_mat_411_read(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradx1_mat_411_read),
    .gradx_2_41_din(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradx_2_41_din),
    .gradx_2_41_full_n(grady_2_data_full_n),
    .gradx_2_41_write(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradx_2_41_write),
    .img_height_dout(img_height_c35_dout),
    .img_height_empty_n(img_height_c35_empty_n),
    .img_height_read(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_img_height_read),
    .img_width_dout(img_width_c36_dout),
    .img_width_empty_n(img_width_c36_empty_n),
    .img_width_read(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_img_width_read)
);

cornerTracker_xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_s xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_start),
    .ap_done(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_done),
    .ap_continue(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_continue),
    .ap_idle(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_idle),
    .ap_ready(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_ready),
    .gradx2_mat_413_dout(gradx2_mat_data_dout),
    .gradx2_mat_413_empty_n(gradx2_mat_data_empty_n),
    .gradx2_mat_413_read(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradx2_mat_413_read),
    .grady2_mat_414_dout(grady2_mat_data_dout),
    .grady2_mat_414_empty_n(grady2_mat_data_empty_n),
    .grady2_mat_414_read(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_grady2_mat_414_read),
    .gradxy_43_din(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradxy_43_din),
    .gradxy_43_full_n(gradxy_data_full_n),
    .gradxy_43_write(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradxy_43_write),
    .img_height_dout(img_height_c32_dout),
    .img_height_empty_n(img_height_c32_empty_n),
    .img_height_read(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_img_height_read),
    .img_width_dout(img_width_c34_dout),
    .img_width_empty_n(img_width_c34_empty_n),
    .img_width_read(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_img_width_read)
);

cornerTracker_boxFilter_0_3_2_1080_1920_1_false_26 boxFilter_0_3_2_1080_1920_1_false_26_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(boxFilter_0_3_2_1080_1920_1_false_26_U0_ap_start),
    .ap_done(boxFilter_0_3_2_1080_1920_1_false_26_U0_ap_done),
    .ap_continue(boxFilter_0_3_2_1080_1920_1_false_26_U0_ap_continue),
    .ap_idle(boxFilter_0_3_2_1080_1920_1_false_26_U0_ap_idle),
    .ap_ready(boxFilter_0_3_2_1080_1920_1_false_26_U0_ap_ready),
    .gradx_2_41_dout(gradx_2_data_dout),
    .gradx_2_41_empty_n(gradx_2_data_empty_n),
    .gradx_2_41_read(boxFilter_0_3_2_1080_1920_1_false_26_U0_gradx_2_41_read),
    .gradx2g_44_din(boxFilter_0_3_2_1080_1920_1_false_26_U0_gradx2g_44_din),
    .gradx2g_44_full_n(gradx2g_data_full_n),
    .gradx2g_44_write(boxFilter_0_3_2_1080_1920_1_false_26_U0_gradx2g_44_write),
    .p_src_mat_1_dout(gradx_2_rows_c_dout),
    .p_src_mat_1_empty_n(gradx_2_rows_c_empty_n),
    .p_src_mat_1_read(boxFilter_0_3_2_1080_1920_1_false_26_U0_p_src_mat_1_read),
    .p_src_mat_2_dout(gradx_2_cols_c_dout),
    .p_src_mat_2_empty_n(gradx_2_cols_c_empty_n),
    .p_src_mat_2_read(boxFilter_0_3_2_1080_1920_1_false_26_U0_p_src_mat_2_read)
);

cornerTracker_boxFilter_0_3_2_1080_1920_1_false_27 boxFilter_0_3_2_1080_1920_1_false_27_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(boxFilter_0_3_2_1080_1920_1_false_27_U0_ap_start),
    .ap_done(boxFilter_0_3_2_1080_1920_1_false_27_U0_ap_done),
    .ap_continue(boxFilter_0_3_2_1080_1920_1_false_27_U0_ap_continue),
    .ap_idle(boxFilter_0_3_2_1080_1920_1_false_27_U0_ap_idle),
    .ap_ready(boxFilter_0_3_2_1080_1920_1_false_27_U0_ap_ready),
    .gradx_2_41_dout(grady_2_data_dout),
    .gradx_2_41_empty_n(grady_2_data_empty_n),
    .gradx_2_41_read(boxFilter_0_3_2_1080_1920_1_false_27_U0_gradx_2_41_read),
    .gradx2g_44_din(boxFilter_0_3_2_1080_1920_1_false_27_U0_gradx2g_44_din),
    .gradx2g_44_full_n(grady2g_data_full_n),
    .gradx2g_44_write(boxFilter_0_3_2_1080_1920_1_false_27_U0_gradx2g_44_write),
    .p_src_mat_1_dout(grady_2_rows_c_dout),
    .p_src_mat_1_empty_n(grady_2_rows_c_empty_n),
    .p_src_mat_1_read(boxFilter_0_3_2_1080_1920_1_false_27_U0_p_src_mat_1_read),
    .p_src_mat_2_dout(grady_2_cols_c_dout),
    .p_src_mat_2_empty_n(grady_2_cols_c_empty_n),
    .p_src_mat_2_read(boxFilter_0_3_2_1080_1920_1_false_27_U0_p_src_mat_2_read)
);

cornerTracker_boxFilter_0_3_2_1080_1920_1_false_s boxFilter_0_3_2_1080_1920_1_false_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(boxFilter_0_3_2_1080_1920_1_false_U0_ap_start),
    .ap_done(boxFilter_0_3_2_1080_1920_1_false_U0_ap_done),
    .ap_continue(boxFilter_0_3_2_1080_1920_1_false_U0_ap_continue),
    .ap_idle(boxFilter_0_3_2_1080_1920_1_false_U0_ap_idle),
    .ap_ready(boxFilter_0_3_2_1080_1920_1_false_U0_ap_ready),
    .gradx_2_41_dout(gradxy_data_dout),
    .gradx_2_41_empty_n(gradxy_data_empty_n),
    .gradx_2_41_read(boxFilter_0_3_2_1080_1920_1_false_U0_gradx_2_41_read),
    .gradx2g_44_din(boxFilter_0_3_2_1080_1920_1_false_U0_gradx2g_44_din),
    .gradx2g_44_full_n(gradxyg_data_full_n),
    .gradx2g_44_write(boxFilter_0_3_2_1080_1920_1_false_U0_gradx2g_44_write),
    .p_src_mat_1_dout(gradxy_rows_c_dout),
    .p_src_mat_1_empty_n(gradxy_rows_c_empty_n),
    .p_src_mat_1_read(boxFilter_0_3_2_1080_1920_1_false_U0_p_src_mat_1_read),
    .p_src_mat_2_dout(gradxy_cols_c_dout),
    .p_src_mat_2_empty_n(gradxy_cols_c_empty_n),
    .p_src_mat_2_read(boxFilter_0_3_2_1080_1920_1_false_U0_p_src_mat_2_read)
);

cornerTracker_xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_s xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_ap_start),
    .ap_done(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_ap_done),
    .ap_continue(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_ap_continue),
    .ap_idle(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_ap_idle),
    .ap_ready(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_ap_ready),
    .gradx2g_44_dout(gradx2g_data_dout),
    .gradx2g_44_empty_n(gradx2g_data_empty_n),
    .gradx2g_44_read(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_gradx2g_44_read),
    .grady2g_45_dout(grady2g_data_dout),
    .grady2g_45_empty_n(grady2g_data_empty_n),
    .grady2g_45_read(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_grady2g_45_read),
    .gradxyg_46_dout(gradxyg_data_dout),
    .gradxyg_46_empty_n(gradxyg_data_empty_n),
    .gradxyg_46_read(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_gradxyg_46_read),
    .score_47_din(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_score_47_din),
    .score_47_full_n(score_data_full_n),
    .score_47_write(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_score_47_write),
    .img_height_dout(img_height_c37_dout),
    .img_height_empty_n(img_height_c37_empty_n),
    .img_height_read(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_height_read),
    .img_width_dout(img_width_c38_dout),
    .img_width_empty_n(img_width_c38_empty_n),
    .img_width_read(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_width_read),
    .img_height_out_din(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_height_out_din),
    .img_height_out_full_n(img_height_c39_full_n),
    .img_height_out_write(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_height_out_write),
    .img_width_out_din(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_width_out_din),
    .img_width_out_full_n(img_width_c40_full_n),
    .img_width_out_write(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_width_out_write)
);

cornerTracker_xFThreshold_5_1080_1920_5_1_12_1920_s xFThreshold_5_1080_1920_5_1_12_1920_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFThreshold_5_1080_1920_5_1_12_1920_U0_ap_start),
    .start_full_n(start_for_xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_full_n),
    .ap_done(xFThreshold_5_1080_1920_5_1_12_1920_U0_ap_done),
    .ap_continue(xFThreshold_5_1080_1920_5_1_12_1920_U0_ap_continue),
    .ap_idle(xFThreshold_5_1080_1920_5_1_12_1920_U0_ap_idle),
    .ap_ready(xFThreshold_5_1080_1920_5_1_12_1920_U0_ap_ready),
    .start_out(xFThreshold_5_1080_1920_5_1_12_1920_U0_start_out),
    .start_write(xFThreshold_5_1080_1920_5_1_12_1920_U0_start_write),
    .score_47_dout(score_data_dout),
    .score_47_empty_n(score_data_empty_n),
    .score_47_read(xFThreshold_5_1080_1920_5_1_12_1920_U0_score_47_read),
    .thresh_48_din(xFThreshold_5_1080_1920_5_1_12_1920_U0_thresh_48_din),
    .thresh_48_full_n(thresh_data_full_n),
    .thresh_48_write(xFThreshold_5_1080_1920_5_1_12_1920_U0_thresh_48_write),
    .threshold_dout(p_threshold_c_dout),
    .threshold_empty_n(p_threshold_c_empty_n),
    .threshold_read(xFThreshold_5_1080_1920_5_1_12_1920_U0_threshold_read),
    .img_height_dout(img_height_c39_dout),
    .img_height_empty_n(img_height_c39_empty_n),
    .img_height_read(xFThreshold_5_1080_1920_5_1_12_1920_U0_img_height_read),
    .img_width_dout(img_width_c40_dout),
    .img_width_empty_n(img_width_c40_empty_n),
    .img_width_read(xFThreshold_5_1080_1920_5_1_12_1920_U0_img_width_read),
    .img_height_out_din(xFThreshold_5_1080_1920_5_1_12_1920_U0_img_height_out_din),
    .img_height_out_full_n(img_height_c41_full_n),
    .img_height_out_write(xFThreshold_5_1080_1920_5_1_12_1920_U0_img_height_out_write),
    .img_width_out_din(xFThreshold_5_1080_1920_5_1_12_1920_U0_img_width_out_din),
    .img_width_out_full_n(img_width_c42_full_n),
    .img_width_out_write(xFThreshold_5_1080_1920_5_1_12_1920_U0_img_width_out_write)
);

cornerTracker_xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_s xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_start),
    .ap_done(xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_done),
    .ap_continue(xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_continue),
    .ap_idle(xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_idle),
    .ap_ready(xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_ready),
    .thresh_48_dout(thresh_data_dout),
    .thresh_48_empty_n(thresh_data_empty_n),
    .thresh_48_read(xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_thresh_48_read),
    .out_harris_mat_420_din(xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_out_harris_mat_420_din),
    .out_harris_mat_420_full_n(out_harris_mat_420_full_n),
    .out_harris_mat_420_write(xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_out_harris_mat_420_write),
    .img_height_dout(img_height_c41_dout),
    .img_height_empty_n(img_height_c41_empty_n),
    .img_height_read(xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_img_height_read),
    .img_width_dout(img_width_c42_dout),
    .img_width_empty_n(img_width_c42_empty_n),
    .img_width_read(xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_img_width_read)
);

cornerTracker_fifo_w11_d2_S_x p_src_mat_1_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_src_mat_1_out_din),
    .if_full_n(p_src_mat_1_c_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_src_mat_1_out_write),
    .if_dout(p_src_mat_1_c_dout),
    .if_empty_n(p_src_mat_1_c_empty_n),
    .if_read(Sobel_0_3_0_2_1080_1920_1_false_U0_p_src_mat_1_read)
);

cornerTracker_fifo_w11_d2_S_x p_src_mat_2_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_src_mat_2_out_din),
    .if_full_n(p_src_mat_2_c_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_src_mat_2_out_write),
    .if_dout(p_src_mat_2_c_dout),
    .if_empty_n(p_src_mat_2_c_empty_n),
    .if_read(Sobel_0_3_0_2_1080_1920_1_false_U0_p_src_mat_2_read)
);

cornerTracker_fifo_w11_d2_S_x img_height_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out_din),
    .if_full_n(img_height_c_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out_write),
    .if_dout(img_height_c_dout),
    .if_empty_n(img_height_c_empty_n),
    .if_read(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_height_read)
);

cornerTracker_fifo_w11_d3_S img_height_c27_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out1_din),
    .if_full_n(img_height_c27_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out1_write),
    .if_dout(img_height_c27_dout),
    .if_empty_n(img_height_c27_empty_n),
    .if_read(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_read)
);

cornerTracker_fifo_w11_d3_S img_height_c28_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out2_din),
    .if_full_n(img_height_c28_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_height_out2_write),
    .if_dout(img_height_c28_dout),
    .if_empty_n(img_height_c28_empty_n),
    .if_read(xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_height_read)
);

cornerTracker_fifo_w11_d2_S_x img_width_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out_din),
    .if_full_n(img_width_c_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out_write),
    .if_dout(img_width_c_dout),
    .if_empty_n(img_width_c_empty_n),
    .if_read(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_width_read)
);

cornerTracker_fifo_w11_d3_S img_width_c29_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out3_din),
    .if_full_n(img_width_c29_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out3_write),
    .if_dout(img_width_c29_dout),
    .if_empty_n(img_width_c29_empty_n),
    .if_read(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_read)
);

cornerTracker_fifo_w11_d3_S img_width_c30_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out4_din),
    .if_full_n(img_width_c30_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_img_width_out4_write),
    .if_dout(img_width_c30_dout),
    .if_empty_n(img_width_c30_empty_n),
    .if_read(xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_width_read)
);

cornerTracker_fifo_w16_d7_S p_threshold_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_threshold_out_din),
    .if_full_n(p_threshold_c_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_p_threshold_out_write),
    .if_dout(p_threshold_c_dout),
    .if_empty_n(p_threshold_c_empty_n),
    .if_read(xFThreshold_5_1080_1920_5_1_12_1920_U0_threshold_read)
);

cornerTracker_fifo_w11_d4_S_x gradx_2_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradx_2_rows_out_din),
    .if_full_n(gradx_2_rows_c_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradx_2_rows_out_write),
    .if_dout(gradx_2_rows_c_dout),
    .if_empty_n(gradx_2_rows_c_empty_n),
    .if_read(boxFilter_0_3_2_1080_1920_1_false_26_U0_p_src_mat_1_read)
);

cornerTracker_fifo_w11_d4_S_x gradx_2_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradx_2_cols_out_din),
    .if_full_n(gradx_2_cols_c_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradx_2_cols_out_write),
    .if_dout(gradx_2_cols_c_dout),
    .if_empty_n(gradx_2_cols_c_empty_n),
    .if_read(boxFilter_0_3_2_1080_1920_1_false_26_U0_p_src_mat_2_read)
);

cornerTracker_fifo_w11_d4_S_x grady_2_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_grady_2_rows_out_din),
    .if_full_n(grady_2_rows_c_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_grady_2_rows_out_write),
    .if_dout(grady_2_rows_c_dout),
    .if_empty_n(grady_2_rows_c_empty_n),
    .if_read(boxFilter_0_3_2_1080_1920_1_false_27_U0_p_src_mat_1_read)
);

cornerTracker_fifo_w11_d4_S_x grady_2_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_grady_2_cols_out_din),
    .if_full_n(grady_2_cols_c_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_grady_2_cols_out_write),
    .if_dout(grady_2_cols_c_dout),
    .if_empty_n(grady_2_cols_c_empty_n),
    .if_read(boxFilter_0_3_2_1080_1920_1_false_27_U0_p_src_mat_2_read)
);

cornerTracker_fifo_w11_d4_S_x gradxy_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradxy_rows_out_din),
    .if_full_n(gradxy_rows_c_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradxy_rows_out_write),
    .if_dout(gradxy_rows_c_dout),
    .if_empty_n(gradxy_rows_c_empty_n),
    .if_read(boxFilter_0_3_2_1080_1920_1_false_U0_p_src_mat_1_read)
);

cornerTracker_fifo_w11_d4_S_x gradxy_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradxy_cols_out_din),
    .if_full_n(gradxy_cols_c_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_gradxy_cols_out_write),
    .if_dout(gradxy_cols_c_dout),
    .if_empty_n(gradxy_cols_c_empty_n),
    .if_read(boxFilter_0_3_2_1080_1920_1_false_U0_p_src_mat_2_read)
);

cornerTracker_fifo_w16_d2_S gradx_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_0_3_0_2_1080_1920_1_false_U0_gradx_mat_49_din),
    .if_full_n(gradx_mat_data_full_n),
    .if_write(Sobel_0_3_0_2_1080_1920_1_false_U0_gradx_mat_49_write),
    .if_dout(gradx_mat_data_dout),
    .if_empty_n(gradx_mat_data_empty_n),
    .if_read(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx_mat_49_read)
);

cornerTracker_fifo_w16_d2_S grady_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_0_3_0_2_1080_1920_1_false_U0_grady_mat_410_din),
    .if_full_n(grady_mat_data_full_n),
    .if_write(Sobel_0_3_0_2_1080_1920_1_false_U0_grady_mat_410_write),
    .if_dout(grady_mat_data_dout),
    .if_empty_n(grady_mat_data_empty_n),
    .if_read(xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx_mat_49_read)
);

cornerTracker_fifo_w16_d2_S gradx1_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx1_mat_411_din),
    .if_full_n(gradx1_mat_data_full_n),
    .if_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx1_mat_411_write),
    .if_dout(gradx1_mat_data_dout),
    .if_empty_n(gradx1_mat_data_empty_n),
    .if_read(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_gradx1_mat_411_read)
);

cornerTracker_fifo_w16_d2_S gradx2_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx2_mat_413_din),
    .if_full_n(gradx2_mat_data_full_n),
    .if_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_gradx2_mat_413_write),
    .if_dout(gradx2_mat_data_dout),
    .if_empty_n(gradx2_mat_data_empty_n),
    .if_read(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradx2_mat_413_read)
);

cornerTracker_fifo_w11_d2_S_x img_height_c31_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_out_din),
    .if_full_n(img_height_c31_full_n),
    .if_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_out_write),
    .if_dout(img_height_c31_dout),
    .if_empty_n(img_height_c31_empty_n),
    .if_read(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_height_read)
);

cornerTracker_fifo_w11_d2_S_x img_height_c32_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_out1_din),
    .if_full_n(img_height_c32_full_n),
    .if_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_height_out1_write),
    .if_dout(img_height_c32_dout),
    .if_empty_n(img_height_c32_empty_n),
    .if_read(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_img_height_read)
);

cornerTracker_fifo_w11_d2_S_x img_width_c33_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_out_din),
    .if_full_n(img_width_c33_full_n),
    .if_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_out_write),
    .if_dout(img_width_c33_dout),
    .if_empty_n(img_width_c33_empty_n),
    .if_read(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_width_read)
);

cornerTracker_fifo_w11_d2_S_x img_width_c34_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_out2_din),
    .if_full_n(img_width_c34_full_n),
    .if_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_img_width_out2_write),
    .if_dout(img_width_c34_dout),
    .if_empty_n(img_width_c34_empty_n),
    .if_read(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_img_width_read)
);

cornerTracker_fifo_w16_d2_S grady1_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx1_mat_411_din),
    .if_full_n(grady1_mat_data_full_n),
    .if_write(xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx1_mat_411_write),
    .if_dout(grady1_mat_data_dout),
    .if_empty_n(grady1_mat_data_empty_n),
    .if_read(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradx1_mat_411_read)
);

cornerTracker_fifo_w16_d2_S grady2_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx2_mat_413_din),
    .if_full_n(grady2_mat_data_full_n),
    .if_write(xFDuplicate_2_1080_1920_3_1_5_1920_U0_gradx2_mat_413_write),
    .if_dout(grady2_mat_data_dout),
    .if_empty_n(grady2_mat_data_empty_n),
    .if_read(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_grady2_mat_414_read)
);

cornerTracker_fifo_w11_d2_S_x img_height_c35_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_height_out_din),
    .if_full_n(img_height_c35_full_n),
    .if_write(xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_height_out_write),
    .if_dout(img_height_c35_dout),
    .if_empty_n(img_height_c35_empty_n),
    .if_read(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_img_height_read)
);

cornerTracker_fifo_w11_d2_S_x img_width_c36_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_width_out_din),
    .if_full_n(img_width_c36_full_n),
    .if_write(xFDuplicate_2_1080_1920_3_1_5_1920_U0_img_width_out_write),
    .if_dout(img_width_c36_dout),
    .if_empty_n(img_width_c36_empty_n),
    .if_read(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_img_width_read)
);

cornerTracker_fifo_w16_d2_S gradx_2_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_gradx_2_41_din),
    .if_full_n(gradx_2_data_full_n),
    .if_write(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_gradx_2_41_write),
    .if_dout(gradx_2_data_dout),
    .if_empty_n(gradx_2_data_empty_n),
    .if_read(boxFilter_0_3_2_1080_1920_1_false_26_U0_gradx_2_41_read)
);

cornerTracker_fifo_w11_d3_S img_height_c37_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_height_out_din),
    .if_full_n(img_height_c37_full_n),
    .if_write(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_height_out_write),
    .if_dout(img_height_c37_dout),
    .if_empty_n(img_height_c37_empty_n),
    .if_read(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_height_read)
);

cornerTracker_fifo_w11_d3_S img_width_c38_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_width_out_din),
    .if_full_n(img_width_c38_full_n),
    .if_write(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_img_width_out_write),
    .if_dout(img_width_c38_dout),
    .if_empty_n(img_width_c38_empty_n),
    .if_read(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_width_read)
);

cornerTracker_fifo_w16_d2_S grady_2_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradx_2_41_din),
    .if_full_n(grady_2_data_full_n),
    .if_write(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradx_2_41_write),
    .if_dout(grady_2_data_dout),
    .if_empty_n(grady_2_data_empty_n),
    .if_read(boxFilter_0_3_2_1080_1920_1_false_27_U0_gradx_2_41_read)
);

cornerTracker_fifo_w16_d2_S gradxy_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradxy_43_din),
    .if_full_n(gradxy_data_full_n),
    .if_write(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_gradxy_43_write),
    .if_dout(gradxy_data_dout),
    .if_empty_n(gradxy_data_empty_n),
    .if_read(boxFilter_0_3_2_1080_1920_1_false_U0_gradx_2_41_read)
);

cornerTracker_fifo_w16_d2_S gradx2g_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(boxFilter_0_3_2_1080_1920_1_false_26_U0_gradx2g_44_din),
    .if_full_n(gradx2g_data_full_n),
    .if_write(boxFilter_0_3_2_1080_1920_1_false_26_U0_gradx2g_44_write),
    .if_dout(gradx2g_data_dout),
    .if_empty_n(gradx2g_data_empty_n),
    .if_read(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_gradx2g_44_read)
);

cornerTracker_fifo_w16_d2_S grady2g_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(boxFilter_0_3_2_1080_1920_1_false_27_U0_gradx2g_44_din),
    .if_full_n(grady2g_data_full_n),
    .if_write(boxFilter_0_3_2_1080_1920_1_false_27_U0_gradx2g_44_write),
    .if_dout(grady2g_data_dout),
    .if_empty_n(grady2g_data_empty_n),
    .if_read(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_grady2g_45_read)
);

cornerTracker_fifo_w16_d2_S gradxyg_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(boxFilter_0_3_2_1080_1920_1_false_U0_gradx2g_44_din),
    .if_full_n(gradxyg_data_full_n),
    .if_write(boxFilter_0_3_2_1080_1920_1_false_U0_gradx2g_44_write),
    .if_dout(gradxyg_data_dout),
    .if_empty_n(gradxyg_data_empty_n),
    .if_read(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_gradxyg_46_read)
);

cornerTracker_fifo_w32_d2_S_x score_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_score_47_din),
    .if_full_n(score_data_full_n),
    .if_write(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_score_47_write),
    .if_dout(score_data_dout),
    .if_empty_n(score_data_empty_n),
    .if_read(xFThreshold_5_1080_1920_5_1_12_1920_U0_score_47_read)
);

cornerTracker_fifo_w11_d2_S_x img_height_c39_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_height_out_din),
    .if_full_n(img_height_c39_full_n),
    .if_write(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_height_out_write),
    .if_dout(img_height_c39_dout),
    .if_empty_n(img_height_c39_empty_n),
    .if_read(xFThreshold_5_1080_1920_5_1_12_1920_U0_img_height_read)
);

cornerTracker_fifo_w11_d2_S_x img_width_c40_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_width_out_din),
    .if_full_n(img_width_c40_full_n),
    .if_write(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_img_width_out_write),
    .if_dout(img_width_c40_dout),
    .if_empty_n(img_width_c40_empty_n),
    .if_read(xFThreshold_5_1080_1920_5_1_12_1920_U0_img_width_read)
);

cornerTracker_fifo_w32_d2_S_x thresh_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFThreshold_5_1080_1920_5_1_12_1920_U0_thresh_48_din),
    .if_full_n(thresh_data_full_n),
    .if_write(xFThreshold_5_1080_1920_5_1_12_1920_U0_thresh_48_write),
    .if_dout(thresh_data_dout),
    .if_empty_n(thresh_data_empty_n),
    .if_read(xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_thresh_48_read)
);

cornerTracker_fifo_w11_d2_S_x img_height_c41_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFThreshold_5_1080_1920_5_1_12_1920_U0_img_height_out_din),
    .if_full_n(img_height_c41_full_n),
    .if_write(xFThreshold_5_1080_1920_5_1_12_1920_U0_img_height_out_write),
    .if_dout(img_height_c41_dout),
    .if_empty_n(img_height_c41_empty_n),
    .if_read(xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_img_height_read)
);

cornerTracker_fifo_w11_d2_S_x img_width_c42_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFThreshold_5_1080_1920_5_1_12_1920_U0_img_width_out_din),
    .if_full_n(img_width_c42_full_n),
    .if_write(xFThreshold_5_1080_1920_5_1_12_1920_U0_img_width_out_write),
    .if_dout(img_width_c42_dout),
    .if_empty_n(img_width_c42_empty_n),
    .if_read(xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_img_width_read)
);

cornerTracker_start_for_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Bbkb start_for_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Bbkb_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_din),
    .if_full_n(start_for_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_start_write),
    .if_dout(start_for_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_dout),
    .if_empty_n(start_for_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_empty_n),
    .if_read(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready)
);

cornerTracker_start_for_xFDuplicate_2_1080_1920_3_1_5_1920_24_U0 start_for_xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_din),
    .if_full_n(start_for_xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_start_write),
    .if_dout(start_for_xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_dout),
    .if_empty_n(start_for_xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_empty_n),
    .if_read(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_ap_ready)
);

cornerTracker_start_for_xFDuplicate_2_1080_1920_3_1_5_1920_U0 start_for_xFDuplicate_2_1080_1920_3_1_5_1920_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFDuplicate_2_1080_1920_3_1_5_1920_U0_din),
    .if_full_n(start_for_xFDuplicate_2_1080_1920_3_1_5_1920_U0_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_start_write),
    .if_dout(start_for_xFDuplicate_2_1080_1920_3_1_5_1920_U0_dout),
    .if_empty_n(start_for_xFDuplicate_2_1080_1920_3_1_5_1920_U0_empty_n),
    .if_read(xFDuplicate_2_1080_1920_3_1_5_1920_U0_ap_ready)
);

cornerTracker_start_for_xFThreshold_5_1080_1920_5_1_12_1920_U0 start_for_xFThreshold_5_1080_1920_5_1_12_1920_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFThreshold_5_1080_1920_5_1_12_1920_U0_din),
    .if_full_n(start_for_xFThreshold_5_1080_1920_5_1_12_1920_U0_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_start_write),
    .if_dout(start_for_xFThreshold_5_1080_1920_5_1_12_1920_U0_dout),
    .if_empty_n(start_for_xFThreshold_5_1080_1920_5_1_12_1920_U0_empty_n),
    .if_read(xFThreshold_5_1080_1920_5_1_12_1920_U0_ap_ready)
);

cornerTracker_start_for_boxFilter_0_3_2_1080_1920_1_false_26_U0 start_for_boxFilter_0_3_2_1080_1920_1_false_26_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_boxFilter_0_3_2_1080_1920_1_false_26_U0_din),
    .if_full_n(start_for_boxFilter_0_3_2_1080_1920_1_false_26_U0_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write),
    .if_dout(start_for_boxFilter_0_3_2_1080_1920_1_false_26_U0_dout),
    .if_empty_n(start_for_boxFilter_0_3_2_1080_1920_1_false_26_U0_empty_n),
    .if_read(boxFilter_0_3_2_1080_1920_1_false_26_U0_ap_ready)
);

cornerTracker_start_for_boxFilter_0_3_2_1080_1920_1_false_27_U0 start_for_boxFilter_0_3_2_1080_1920_1_false_27_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_boxFilter_0_3_2_1080_1920_1_false_27_U0_din),
    .if_full_n(start_for_boxFilter_0_3_2_1080_1920_1_false_27_U0_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write),
    .if_dout(start_for_boxFilter_0_3_2_1080_1920_1_false_27_U0_dout),
    .if_empty_n(start_for_boxFilter_0_3_2_1080_1920_1_false_27_U0_empty_n),
    .if_read(boxFilter_0_3_2_1080_1920_1_false_27_U0_ap_ready)
);

cornerTracker_start_for_boxFilter_0_3_2_1080_1920_1_false_U0 start_for_boxFilter_0_3_2_1080_1920_1_false_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_boxFilter_0_3_2_1080_1920_1_false_U0_din),
    .if_full_n(start_for_boxFilter_0_3_2_1080_1920_1_false_U0_full_n),
    .if_write(xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write),
    .if_dout(start_for_boxFilter_0_3_2_1080_1920_1_false_U0_dout),
    .if_empty_n(start_for_boxFilter_0_3_2_1080_1920_1_false_U0_empty_n),
    .if_read(boxFilter_0_3_2_1080_1920_1_false_U0_ap_ready)
);

cornerTracker_start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0 start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_din),
    .if_full_n(start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_full_n),
    .if_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_start_write),
    .if_dout(start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_dout),
    .if_empty_n(start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_empty_n),
    .if_read(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_ap_ready)
);

cornerTracker_start_for_xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0 start_for_xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_din),
    .if_full_n(start_for_xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_full_n),
    .if_write(xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_start_write),
    .if_dout(start_for_xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_dout),
    .if_empty_n(start_for_xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_empty_n),
    .if_read(xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_ready)
);

cornerTracker_start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0 start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_din),
    .if_full_n(start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_full_n),
    .if_write(xFDuplicate_2_1080_1920_3_1_5_1920_U0_start_write),
    .if_dout(start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_dout),
    .if_empty_n(start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_empty_n),
    .if_read(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_ready)
);

cornerTracker_start_for_xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0 start_for_xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_din),
    .if_full_n(start_for_xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_full_n),
    .if_write(xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_start_write),
    .if_dout(start_for_xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_dout),
    .if_empty_n(start_for_xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_empty_n),
    .if_read(xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_ap_ready)
);

cornerTracker_start_for_xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0 start_for_xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_din),
    .if_full_n(start_for_xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_full_n),
    .if_write(xFThreshold_5_1080_1920_5_1_12_1920_U0_start_write),
    .if_dout(start_for_xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_dout),
    .if_empty_n(start_for_xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_empty_n),
    .if_read(xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready <= ap_sync_Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready <= ap_sync_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (1'b0 == Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready))) begin
        Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready_count <= (Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (1'b1 == Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready))) begin
        Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready_count <= (Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready == 1'b0))) begin
        xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready_count <= (xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready == 1'b1))) begin
        xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready_count <= (xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready_count + 2'd1);
    end
end

assign Sobel_0_3_0_2_1080_1920_1_false_U0_ap_continue = 1'b1;

assign Sobel_0_3_0_2_1080_1920_1_false_U0_ap_start = ((ap_sync_reg_Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready ^ 1'b1) & ap_start);

assign Sobel_0_3_0_2_1080_1920_1_false_U0_start_full_n = 1'b1;

assign Sobel_0_3_0_2_1080_1920_1_false_U0_start_write = 1'b0;

assign ap_done = xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_done;

assign ap_idle = (xFThreshold_5_1080_1920_5_1_12_1920_U0_ap_idle & xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_idle & xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_ap_idle & xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_idle & xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_idle & xFDuplicate_2_1080_1920_3_1_5_1920_U0_ap_idle & xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_ap_idle & xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_idle & xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_idle & xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_ap_idle & boxFilter_0_3_2_1080_1920_1_false_U0_ap_idle & boxFilter_0_3_2_1080_1920_1_false_27_U0_ap_idle & boxFilter_0_3_2_1080_1920_1_false_26_U0_ap_idle & Sobel_0_3_0_2_1080_1920_1_false_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready = (ap_sync_reg_Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready | Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready);

assign ap_sync_continue = ap_continue;

assign ap_sync_done = xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_done;

assign ap_sync_ready = (ap_sync_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready & ap_sync_Sobel_0_3_0_2_1080_1920_1_false_U0_ap_ready);

assign ap_sync_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready = (xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready | ap_sync_reg_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready);

assign boxFilter_0_3_2_1080_1920_1_false_26_U0_ap_continue = 1'b1;

assign boxFilter_0_3_2_1080_1920_1_false_26_U0_ap_start = start_for_boxFilter_0_3_2_1080_1920_1_false_26_U0_empty_n;

assign boxFilter_0_3_2_1080_1920_1_false_26_U0_start_full_n = 1'b1;

assign boxFilter_0_3_2_1080_1920_1_false_26_U0_start_write = 1'b0;

assign boxFilter_0_3_2_1080_1920_1_false_27_U0_ap_continue = 1'b1;

assign boxFilter_0_3_2_1080_1920_1_false_27_U0_ap_start = start_for_boxFilter_0_3_2_1080_1920_1_false_27_U0_empty_n;

assign boxFilter_0_3_2_1080_1920_1_false_27_U0_start_full_n = 1'b1;

assign boxFilter_0_3_2_1080_1920_1_false_27_U0_start_write = 1'b0;

assign boxFilter_0_3_2_1080_1920_1_false_U0_ap_continue = 1'b1;

assign boxFilter_0_3_2_1080_1920_1_false_U0_ap_start = start_for_boxFilter_0_3_2_1080_1920_1_false_U0_empty_n;

assign boxFilter_0_3_2_1080_1920_1_false_U0_start_full_n = 1'b1;

assign boxFilter_0_3_2_1080_1920_1_false_U0_start_write = 1'b0;

assign in_harris_mat_419_read = Sobel_0_3_0_2_1080_1920_1_false_U0_in_harris_mat_419_read;

assign out_harris_mat_420_din = xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_out_harris_mat_420_din;

assign out_harris_mat_420_write = xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_out_harris_mat_420_write;

assign start_for_boxFilter_0_3_2_1080_1920_1_false_26_U0_din = 1'b1;

assign start_for_boxFilter_0_3_2_1080_1920_1_false_27_U0_din = 1'b1;

assign start_for_boxFilter_0_3_2_1080_1920_1_false_U0_din = 1'b1;

assign start_for_xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_din = 1'b1;

assign start_for_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_din = 1'b1;

assign start_for_xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_din = 1'b1;

assign start_for_xFDuplicate_2_1080_1920_3_1_5_1920_U0_din = 1'b1;

assign start_for_xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_din = 1'b1;

assign start_for_xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_din = 1'b1;

assign start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_din = 1'b1;

assign start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_din = 1'b1;

assign start_for_xFThreshold_5_1080_1920_5_1_12_1920_U0_din = 1'b1;

assign xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_ap_continue = 1'b1;

assign xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_ap_start = start_for_xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_empty_n;

assign xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_start_full_n = 1'b1;

assign xFComputeScore_2_5_1080_1920_3_5_1_5_12_1920_U0_start_write = 1'b0;

assign xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue = 1'b1;

assign xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_start = start_for_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_empty_n;

assign xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_full_n = (start_for_boxFilter_0_3_2_1080_1920_1_false_U0_full_n & start_for_boxFilter_0_3_2_1080_1920_1_false_27_U0_full_n & start_for_boxFilter_0_3_2_1080_1920_1_false_26_U0_full_n);

assign xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_continue = 1'b1;

assign xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_start = ((ap_sync_reg_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_ap_ready ^ 1'b1) & ap_start);

assign xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_entry50_U0_start_full_n = (start_for_xFThreshold_5_1080_1920_5_1_12_1920_U0_full_n & start_for_xFDuplicate_2_1080_1920_3_1_5_1920_U0_full_n & start_for_xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_full_n & start_for_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_Block_ZN2xf2cv3MatILi2ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_full_n);

assign xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_ap_continue = 1'b1;

assign xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_ap_start = start_for_xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_empty_n;

assign xFDuplicate_2_1080_1920_3_1_5_1920_24_U0_start_full_n = (start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_full_n & start_for_xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_full_n);

assign xFDuplicate_2_1080_1920_3_1_5_1920_U0_ap_continue = 1'b1;

assign xFDuplicate_2_1080_1920_3_1_5_1920_U0_ap_start = start_for_xFDuplicate_2_1080_1920_3_1_5_1920_U0_empty_n;

assign xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_continue = ap_continue;

assign xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_ap_start = start_for_xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_empty_n;

assign xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_start_full_n = 1'b1;

assign xFMaxSuppression_5_0_1080_1920_5_0_1_12_1_U0_start_write = 1'b0;

assign xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_continue = 1'b1;

assign xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_start = start_for_xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_empty_n;

assign xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_start_full_n = 1'b1;

assign xFMultiply_2_2_1080_1920_3_3_1_5_5_1920_int_U0_start_write = 1'b0;

assign xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_ap_continue = 1'b1;

assign xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_ap_start = start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_25_U0_empty_n;

assign xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_continue = 1'b1;

assign xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_ap_start = start_for_xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_empty_n;

assign xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_start_full_n = 1'b1;

assign xFSquare_2_2_1080_1920_3_3_1_5_5_1920_int_U0_start_write = 1'b0;

assign xFThreshold_5_1080_1920_5_1_12_1920_U0_ap_continue = 1'b1;

assign xFThreshold_5_1080_1920_5_1_12_1920_U0_ap_start = start_for_xFThreshold_5_1080_1920_5_1_12_1920_U0_empty_n;

endmodule //cornerTracker_xFCornerHarrisDetector_3_3_0_1080_1920_1_0_1_1_12_1920_5_12_false_s
