// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pyr_dense_optical_flow_accel_scale_up_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_false_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        strmFlowV_split_dout,
        strmFlowV_split_empty_n,
        strmFlowV_split_read,
        strmFlowV_scaled_din,
        strmFlowV_scaled_full_n,
        strmFlowV_scaled_write,
        prev_rows_dout,
        prev_rows_empty_n,
        prev_rows_read,
        prev_cols_dout,
        prev_cols_empty_n,
        prev_cols_read,
        rows_dout,
        rows_empty_n,
        rows_read,
        cols_dout,
        cols_empty_n,
        cols_read,
        scale_up_flag_dout,
        scale_up_flag_empty_n,
        scale_up_flag_read,
        scale_in_dout,
        scale_in_empty_n,
        scale_in_read
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_pp0_stage0 = 11'd16;
parameter    ap_ST_fsm_state7 = 11'd32;
parameter    ap_ST_fsm_state8 = 11'd64;
parameter    ap_ST_fsm_state9 = 11'd128;
parameter    ap_ST_fsm_state10 = 11'd256;
parameter    ap_ST_fsm_state11 = 11'd512;
parameter    ap_ST_fsm_state12 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] strmFlowV_split_dout;
input   strmFlowV_split_empty_n;
output   strmFlowV_split_read;
output  [15:0] strmFlowV_scaled_din;
input   strmFlowV_scaled_full_n;
output   strmFlowV_scaled_write;
input  [15:0] prev_rows_dout;
input   prev_rows_empty_n;
output   prev_rows_read;
input  [15:0] prev_cols_dout;
input   prev_cols_empty_n;
output   prev_cols_read;
input  [15:0] rows_dout;
input   rows_empty_n;
output   rows_read;
input  [15:0] cols_dout;
input   cols_empty_n;
output   cols_read;
input  [0:0] scale_up_flag_dout;
input   scale_up_flag_empty_n;
output   scale_up_flag_read;
input  [31:0] scale_in_dout;
input   scale_in_empty_n;
output   scale_in_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg strmFlowV_split_read;
reg[15:0] strmFlowV_scaled_din;
reg strmFlowV_scaled_write;
reg prev_rows_read;
reg prev_cols_read;
reg rows_read;
reg cols_read;
reg scale_up_flag_read;
reg scale_in_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    strmFlowV_split_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln318_reg_752;
reg    strmFlowV_scaled_blk_n;
reg    prev_rows_blk_n;
reg    prev_cols_blk_n;
reg    rows_blk_n;
reg    cols_blk_n;
reg    scale_up_flag_blk_n;
reg    scale_in_blk_n;
reg   [15:0] empty_157_reg_205;
reg   [15:0] prev_rows_read_reg_658;
reg    ap_block_state1;
reg   [15:0] prev_cols_read_reg_663;
reg   [15:0] rows_read_reg_668;
reg   [15:0] cols_read_reg_676;
reg   [0:0] scale_up_flag_read_reg_682;
reg   [31:0] scale_in_read_reg_686;
wire   [53:0] select_ln570_fu_372_p3;
reg   [53:0] select_ln570_reg_692;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln571_fu_380_p2;
reg   [0:0] icmp_ln571_reg_697;
wire   [0:0] icmp_ln581_fu_392_p2;
reg   [0:0] icmp_ln581_reg_704;
wire   [11:0] add_ln581_fu_398_p2;
reg   [11:0] add_ln581_reg_711;
wire   [11:0] sub_ln581_fu_404_p2;
reg   [11:0] sub_ln581_reg_716;
wire   [0:0] icmp_ln582_fu_410_p2;
reg   [0:0] icmp_ln582_reg_721;
wire   [16:0] trunc_ln583_fu_416_p1;
reg   [16:0] trunc_ln583_reg_727;
wire   [16:0] scaleI_V_fu_577_p3;
reg   [16:0] scaleI_V_reg_733;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln314_fu_589_p2;
wire    ap_CS_fsm_state4;
wire   [15:0] add_ln695_fu_594_p2;
reg   [15:0] add_ln695_reg_747;
wire   [0:0] icmp_ln318_fu_600_p2;
wire    ap_block_state5_pp0_stage0_iter0;
reg    ap_block_state6_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] add_ln695_4_fu_605_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_CS_fsm_state9;
wire    grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_ready;
wire    grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_done;
wire   [16:0] op2_assign_fu_614_p2;
reg   [16:0] op2_assign_reg_766;
wire   [0:0] icmp_ln882_fu_620_p2;
reg   [0:0] icmp_ln882_reg_772;
reg   [0:0] flagLoaded0_3_load_reg_794;
wire    ap_CS_fsm_state10;
wire   [16:0] zext_ln882_fu_631_p1;
reg   [16:0] zext_ln882_reg_799;
wire   [15:0] add_i_i52_i_i_fu_641_p2;
reg   [15:0] add_i_i52_i_i_reg_807;
reg   [31:0] prevIceil_5_load_reg_813;
wire   [0:0] icmp_ln882_6_fu_636_p2;
reg   [0:0] flagLoaded1_2_load_reg_819;
wire   [0:0] ap_phi_mux_flag_phi_fu_220_p4;
reg   [0:0] flagLoaded1_2_load_1_reg_824;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state5;
reg    buffer_0_V_ce0;
reg    buffer_0_V_we0;
reg    buffer_0_V_ce1;
wire   [15:0] buffer_0_V_q1;
reg    buffer_1_V_ce0;
reg    buffer_1_V_we0;
reg    buffer_1_V_ce1;
wire   [15:0] buffer_1_V_q1;
reg   [10:0] buf0_V_address0;
reg    buf0_V_ce0;
reg    buf0_V_we0;
wire   [15:0] buf0_V_q0;
reg   [10:0] buf1_V_address0;
reg    buf1_V_ce0;
reg    buf1_V_we0;
wire   [15:0] buf1_V_q0;
wire    grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_start;
wire    grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_done;
wire    grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_idle;
wire    grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_ready;
wire   [15:0] grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_strmFlowU_scaled17_din;
wire    grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_strmFlowU_scaled17_write;
wire   [10:0] grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buf_r_address0;
wire    grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buf_r_ce0;
reg   [15:0] grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buf_r_q0;
wire   [10:0] grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_address0;
wire    grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_ce0;
wire    grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_we0;
wire   [15:0] grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_d0;
wire   [10:0] grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_address1;
wire    grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_ce1;
wire   [10:0] grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_address0;
wire    grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_ce0;
wire    grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_we0;
wire   [15:0] grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_d0;
wire   [10:0] grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_address1;
wire    grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_ce1;
reg   [0:0] grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_flagLoaded;
reg   [16:0] grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_row;
wire    grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_start;
wire    grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_idle;
wire    grp_load_data_1920_16_10_45_22_17_1_s_fu_278_strmFlowU_split15_read;
wire   [10:0] grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_address0;
wire    grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_ce0;
wire    grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_we0;
wire   [15:0] grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_d0;
reg   [15:0] grp_load_data_1920_16_10_45_22_17_1_s_fu_278_inCurrRow;
reg   [31:0] grp_load_data_1920_16_10_45_22_17_1_s_fu_278_prevIceil_read_5;
reg   [31:0] grp_load_data_1920_16_10_45_22_17_1_s_fu_278_prevIceil_read;
wire   [0:0] grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_return_0;
wire   [31:0] grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_return_1;
reg   [15:0] empty_reg_194;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln882_5_fu_584_p2;
reg   [0:0] ap_phi_mux_flag_2_phi_fu_253_p4;
reg   [0:0] flag_reg_216;
wire    ap_CS_fsm_state11;
reg    ap_block_state11_on_subcall_done;
reg   [15:0] empty_158_reg_228;
reg   [0:0] flagLoaded0_2_i_i_reg_239;
reg    grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_start_reg;
wire    ap_CS_fsm_state8;
reg   [31:0] prevIceil_5_fu_132;
reg   [0:0] flagLoaded0_3_fu_136;
reg   [0:0] flagLoaded1_2_fu_140;
reg    ap_block_pp0_stage0_01001;
wire   [63:0] grp_fu_294_p1;
wire   [63:0] ireg_fu_320_p1;
wire   [10:0] exp_tmp_V_fu_336_p4;
wire   [51:0] trunc_ln565_fu_350_p1;
wire   [52:0] p_Result_2_fu_354_p3;
wire   [53:0] zext_ln569_fu_362_p1;
wire   [0:0] p_Result_s_fu_328_p3;
wire   [53:0] man_V_2_fu_366_p2;
wire   [62:0] trunc_ln555_fu_324_p1;
wire   [11:0] zext_ln455_fu_346_p1;
wire   [11:0] F2_fu_386_p2;
wire  signed [11:0] sh_amt_fu_420_p3;
wire   [5:0] trunc_ln586_fu_441_p1;
wire   [53:0] zext_ln586_fu_445_p1;
wire   [53:0] ashr_ln586_fu_449_p2;
wire   [31:0] bitcast_ln702_fu_458_p1;
wire   [0:0] tmp_fu_461_p3;
wire  signed [31:0] sext_ln581_fu_425_p1;
wire   [16:0] sext_ln581cast_fu_477_p1;
wire   [0:0] xor_ln571_fu_486_p2;
wire   [0:0] and_ln582_fu_491_p2;
wire   [0:0] or_ln582_fu_503_p2;
wire   [0:0] xor_ln582_fu_507_p2;
wire   [0:0] and_ln581_fu_513_p2;
wire   [0:0] icmp_ln585_fu_429_p2;
wire   [0:0] and_ln585_fu_518_p2;
wire   [16:0] trunc_ln586_2_fu_454_p1;
wire   [16:0] select_ln582_fu_496_p3;
wire   [0:0] xor_ln585_fu_532_p2;
wire   [0:0] and_ln585_2_fu_538_p2;
wire   [16:0] select_ln588_fu_469_p3;
wire   [16:0] select_ln585_fu_524_p3;
wire   [0:0] or_ln581_fu_552_p2;
wire   [0:0] icmp_ln603_fu_435_p2;
wire   [0:0] xor_ln581_fu_557_p2;
wire   [0:0] and_ln603_fu_563_p2;
wire   [16:0] shl_ln604_fu_481_p2;
wire   [16:0] select_ln585_2_fu_544_p3;
wire   [16:0] select_ln603_fu_569_p3;
wire   [16:0] outRows_cast_i_i_fu_611_p1;
reg    grp_fu_294_ce;
reg    ap_predicate_op155_call_state12;
reg    ap_predicate_op157_call_state12;
reg    ap_block_state12_on_subcall_done;
reg   [10:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 11'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_start_reg = 1'b0;
#0 grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_start_reg = 1'b0;
end

pyr_dense_optical_flow_accel_scale_up_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_falsefYi #(
    .DataWidth( 16 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buffer_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_address0),
    .ce0(buffer_0_V_ce0),
    .we0(buffer_0_V_we0),
    .d0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_d0),
    .address1(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_address1),
    .ce1(buffer_0_V_ce1),
    .q1(buffer_0_V_q1)
);

pyr_dense_optical_flow_accel_scale_up_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_falsefYi #(
    .DataWidth( 16 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buffer_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_address0),
    .ce0(buffer_1_V_ce0),
    .we0(buffer_1_V_we0),
    .d0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_d0),
    .address1(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_address1),
    .ce1(buffer_1_V_ce1),
    .q1(buffer_1_V_q1)
);

pyr_dense_optical_flow_accel_scale_up_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_falsehbi #(
    .DataWidth( 16 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buf0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf0_V_address0),
    .ce0(buf0_V_ce0),
    .we0(buf0_V_we0),
    .d0(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_d0),
    .q0(buf0_V_q0)
);

pyr_dense_optical_flow_accel_scale_up_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_falsehbi #(
    .DataWidth( 16 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buf1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf1_V_address0),
    .ce0(buf1_V_ce0),
    .we0(buf1_V_we0),
    .d0(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_d0),
    .q0(buf1_V_q0)
);

pyr_dense_optical_flow_accel_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_start),
    .ap_done(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_done),
    .ap_idle(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_idle),
    .ap_ready(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_ready),
    .strmFlowU_scaled17_din(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_strmFlowU_scaled17_din),
    .strmFlowU_scaled17_full_n(strmFlowV_scaled_full_n),
    .strmFlowU_scaled17_write(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_strmFlowU_scaled17_write),
    .buf_r_address0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buf_r_address0),
    .buf_r_ce0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buf_r_ce0),
    .buf_r_q0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buf_r_q0),
    .buffer_r_address0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_address0),
    .buffer_r_ce0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_ce0),
    .buffer_r_we0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_we0),
    .buffer_r_d0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_d0),
    .buffer_r_address1(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_address1),
    .buffer_r_ce1(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_ce1),
    .buffer_r_q1(buffer_0_V_q1),
    .buffer1_address0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_address0),
    .buffer1_ce0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_ce0),
    .buffer1_we0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_we0),
    .buffer1_d0(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_d0),
    .buffer1_address1(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_address1),
    .buffer1_ce1(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_ce1),
    .buffer1_q1(buffer_1_V_q1),
    .outRows(rows_read_reg_668),
    .outCols(cols_read_reg_676),
    .flagLoaded(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_flagLoaded),
    .row(grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_row),
    .scaleI(scaleI_V_reg_733),
    .scaleJ(scaleI_V_reg_733)
);

pyr_dense_optical_flow_accel_load_data_1920_16_10_45_22_17_1_s grp_load_data_1920_16_10_45_22_17_1_s_fu_278(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_start),
    .ap_done(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_done),
    .ap_idle(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_idle),
    .ap_ready(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_ready),
    .strmFlowU_split15_dout(strmFlowV_split_dout),
    .strmFlowU_split15_empty_n(strmFlowV_split_empty_n),
    .strmFlowU_split15_read(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_strmFlowU_split15_read),
    .buf_r_address0(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_address0),
    .buf_r_ce0(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_ce0),
    .buf_r_we0(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_we0),
    .buf_r_d0(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_d0),
    .rows(prev_rows_read_reg_658),
    .cols(prev_cols_read_reg_663),
    .inCurrRow(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_inCurrRow),
    .scaleI(scaleI_V_reg_733),
    .prevIceil_read_5(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_prevIceil_read_5),
    .prevIceil_read(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_prevIceil_read),
    .ap_return_0(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_return_0),
    .ap_return_1(grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_return_1)
);

pyr_dense_optical_flow_accel_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U228(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(scale_in_dout),
    .ce(grp_fu_294_ce),
    .dout(grp_fu_294_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state5))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln314_fu_589_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state5);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln314_fu_589_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) | ((ap_phi_mux_flag_phi_fu_220_p4 == 1'd0) & (icmp_ln882_6_fu_636_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln882_reg_772 == 1'd1)) | ((ap_phi_mux_flag_phi_fu_220_p4 == 1'd1) & (icmp_ln882_6_fu_636_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln882_reg_772 == 1'd1)))) begin
            grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_start_reg <= 1'b1;
        end else if ((grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_ready == 1'b1)) begin
            grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_start_reg <= 1'b0;
    end else begin
        if ((((ap_phi_mux_flag_phi_fu_220_p4 == 1'd0) & (icmp_ln882_6_fu_636_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln882_reg_772 == 1'd1)) | ((ap_phi_mux_flag_phi_fu_220_p4 == 1'd1) & (icmp_ln882_6_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln882_reg_772 == 1'd1)) | ((ap_phi_mux_flag_phi_fu_220_p4 == 1'd1) & (icmp_ln882_6_fu_636_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln882_reg_772 == 1'd1)) | ((1'b1 == ap_CS_fsm_state10) & ((icmp_ln882_reg_772 == 1'd0) | ((ap_phi_mux_flag_phi_fu_220_p4 == 1'd0) & (icmp_ln882_6_fu_636_p2 == 1'd0)))))) begin
            grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_start_reg <= 1'b1;
        end else if ((grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_ready == 1'b1)) begin
            grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln318_fu_600_p2 == 1'd0))) begin
        empty_157_reg_205 <= add_ln695_4_fu_605_p2;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln314_fu_589_p2 == 1'd0))) begin
        empty_157_reg_205 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln882_fu_620_p2 == 1'd1) & (grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_done == 1'b1))) begin
        empty_158_reg_228 <= 16'd0;
    end else if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
        empty_158_reg_228 <= add_i_i52_i_i_reg_807;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln882_5_fu_584_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (scale_up_flag_read_reg_682 == 1'd0))) begin
        empty_reg_194 <= 16'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        empty_reg_194 <= add_ln695_reg_747;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln882_fu_620_p2 == 1'd0) & (grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_done == 1'b1))) begin
        flagLoaded0_2_i_i_reg_239 <= grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_return_0;
    end else if (((ap_phi_mux_flag_phi_fu_220_p4 == 1'd0) & (icmp_ln882_6_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln882_reg_772 == 1'd1))) begin
        flagLoaded0_2_i_i_reg_239 <= flagLoaded0_3_fu_136;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln882_fu_620_p2 == 1'd1) & (grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_done == 1'b1))) begin
        flag_reg_216 <= 1'd0;
    end else if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
        flag_reg_216 <= ap_phi_mux_flag_2_phi_fu_253_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln882_reg_772 == 1'd1))) begin
        add_i_i52_i_i_reg_807 <= add_i_i52_i_i_fu_641_p2;
        flagLoaded0_3_load_reg_794 <= flagLoaded0_3_fu_136;
        zext_ln882_reg_799[15 : 0] <= zext_ln882_fu_631_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln581_reg_711 <= add_ln581_fu_398_p2;
        icmp_ln571_reg_697 <= icmp_ln571_fu_380_p2;
        icmp_ln581_reg_704 <= icmp_ln581_fu_392_p2;
        icmp_ln582_reg_721 <= icmp_ln582_fu_410_p2;
        select_ln570_reg_692 <= select_ln570_fu_372_p3;
        sub_ln581_reg_716 <= sub_ln581_fu_404_p2;
        trunc_ln583_reg_727 <= trunc_ln583_fu_416_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln695_reg_747 <= add_ln695_fu_594_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((scale_in_empty_n == 1'b0) | (scale_up_flag_empty_n == 1'b0) | (cols_empty_n == 1'b0) | (rows_empty_n == 1'b0) | (prev_cols_empty_n == 1'b0) | (prev_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_read_reg_676 <= cols_dout;
        prev_cols_read_reg_663 <= prev_cols_dout;
        prev_rows_read_reg_658 <= prev_rows_dout;
        rows_read_reg_668 <= rows_dout;
        scale_in_read_reg_686 <= scale_in_dout;
        scale_up_flag_read_reg_682 <= scale_up_flag_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_state11_on_subcall_done) & (flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln882_fu_620_p2 == 1'd1) & (grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_done == 1'b1)))) begin
        flagLoaded0_3_fu_136 <= grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        flagLoaded1_2_fu_140 <= grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_flag_phi_fu_220_p4 == 1'd1) & (icmp_ln882_6_fu_636_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln882_reg_772 == 1'd1))) begin
        flagLoaded1_2_load_1_reg_824 <= flagLoaded1_2_fu_140;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_flag_phi_fu_220_p4 == 1'd1) & (icmp_ln882_6_fu_636_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln882_reg_772 == 1'd1))) begin
        flagLoaded1_2_load_reg_819 <= flagLoaded1_2_fu_140;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln318_reg_752 <= icmp_ln318_fu_600_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_done == 1'b1))) begin
        icmp_ln882_reg_772 <= icmp_ln882_fu_620_p2;
        op2_assign_reg_766 <= op2_assign_fu_614_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_state11_on_subcall_done) & (flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((1'b0 == ap_block_state11_on_subcall_done) & (flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state9) & (icmp_ln882_fu_620_p2 == 1'd1) & (grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_done == 1'b1)))) begin
        prevIceil_5_fu_132 <= grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln882_6_fu_636_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10) & (icmp_ln882_reg_772 == 1'd1))) begin
        prevIceil_5_load_reg_813 <= prevIceil_5_fu_132;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        scaleI_V_reg_733 <= scaleI_V_fu_577_p3;
    end
end

always @ (*) begin
    if ((icmp_ln318_fu_600_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        if ((flag_reg_216 == 1'd0)) begin
            ap_phi_mux_flag_2_phi_fu_253_p4 = 1'd1;
        end else if ((flag_reg_216 == 1'd1)) begin
            ap_phi_mux_flag_2_phi_fu_253_p4 = 1'd0;
        end else begin
            ap_phi_mux_flag_2_phi_fu_253_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_flag_2_phi_fu_253_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)))) begin
        buf0_V_address0 = grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_address0;
    end else if ((((1'b1 == ap_CS_fsm_state12) & (((icmp_ln882_reg_772 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)))) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        buf0_V_address0 = grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buf_r_address0;
    end else begin
        buf0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)))) begin
        buf0_V_ce0 = grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_ce0;
    end else if ((((1'b1 == ap_CS_fsm_state12) & (((icmp_ln882_reg_772 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)))) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        buf0_V_ce0 = grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buf_r_ce0;
    end else begin
        buf0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)))) begin
        buf0_V_we0 = grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_we0;
    end else begin
        buf0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        buf1_V_address0 = grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_address0;
    end else if ((((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln882_reg_772 == 1'd1) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)))) begin
        buf1_V_address0 = grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buf_r_address0;
    end else begin
        buf1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        buf1_V_ce0 = grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_ce0;
    end else if ((((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln882_reg_772 == 1'd1) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)))) begin
        buf1_V_ce0 = grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buf_r_ce0;
    end else begin
        buf1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        buf1_V_we0 = grp_load_data_1920_16_10_45_22_17_1_s_fu_278_buf_r_we0;
    end else begin
        buf1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state12) & (((icmp_ln882_reg_772 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)))) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln882_reg_772 == 1'd1) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        buffer_0_V_ce0 = grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_ce0;
    end else begin
        buffer_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state12) & (((icmp_ln882_reg_772 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)))) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln882_reg_772 == 1'd1) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        buffer_0_V_ce1 = grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_ce1;
    end else begin
        buffer_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state12) & (((icmp_ln882_reg_772 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)))) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln882_reg_772 == 1'd1) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        buffer_0_V_we0 = grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer_r_we0;
    end else begin
        buffer_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state12) & (((icmp_ln882_reg_772 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)))) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln882_reg_772 == 1'd1) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        buffer_1_V_ce0 = grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_ce0;
    end else begin
        buffer_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state12) & (((icmp_ln882_reg_772 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)))) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln882_reg_772 == 1'd1) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        buffer_1_V_ce1 = grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_ce1;
    end else begin
        buffer_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state12) & (((icmp_ln882_reg_772 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)))) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln882_reg_772 == 1'd1) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        buffer_1_V_we0 = grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buffer1_we0;
    end else begin
        buffer_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_blk_n = cols_empty_n;
    end else begin
        cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((scale_in_empty_n == 1'b0) | (scale_up_flag_empty_n == 1'b0) | (cols_empty_n == 1'b0) | (rows_empty_n == 1'b0) | (prev_cols_empty_n == 1'b0) | (prev_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_read = 1'b1;
    end else begin
        cols_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((scale_in_empty_n == 1'b0) | (scale_up_flag_empty_n == 1'b0) | (cols_empty_n == 1'b0) | (rows_empty_n == 1'b0) | (prev_cols_empty_n == 1'b0) | (prev_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_294_ce = 1'b1;
    end else begin
        grp_fu_294_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        grp_load_data_1920_16_10_45_22_17_1_s_fu_278_inCurrRow = add_i_i52_i_i_reg_807;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_load_data_1920_16_10_45_22_17_1_s_fu_278_inCurrRow = 16'd0;
    end else begin
        grp_load_data_1920_16_10_45_22_17_1_s_fu_278_inCurrRow = 'bx;
    end
end

always @ (*) begin
    if ((((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        grp_load_data_1920_16_10_45_22_17_1_s_fu_278_prevIceil_read = prevIceil_5_load_reg_813;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_load_data_1920_16_10_45_22_17_1_s_fu_278_prevIceil_read = 32'd4294967295;
    end else begin
        grp_load_data_1920_16_10_45_22_17_1_s_fu_278_prevIceil_read = 'bx;
    end
end

always @ (*) begin
    if ((((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        grp_load_data_1920_16_10_45_22_17_1_s_fu_278_prevIceil_read_5 = prevIceil_5_load_reg_813;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_load_data_1920_16_10_45_22_17_1_s_fu_278_prevIceil_read_5 = 32'd4294967295;
    end else begin
        grp_load_data_1920_16_10_45_22_17_1_s_fu_278_prevIceil_read_5 = 'bx;
    end
end

always @ (*) begin
    if ((((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln882_reg_772 == 1'd1) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)))) begin
        grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buf_r_q0 = buf1_V_q0;
    end else if ((((1'b1 == ap_CS_fsm_state12) & (((icmp_ln882_reg_772 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)))) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buf_r_q0 = buf0_V_q0;
    end else begin
        grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_buf_r_q0 = 'bx;
    end
end

always @ (*) begin
    if (((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln882_reg_772 == 1'd1) & (scale_up_flag_read_reg_682 == 1'd1))) begin
        grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_flagLoaded = flagLoaded1_2_load_1_reg_824;
    end else if (((1'b1 == ap_CS_fsm_state12) & (((icmp_ln882_reg_772 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1))))) begin
        grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_flagLoaded = flagLoaded0_2_i_i_reg_239;
    end else if (((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_flagLoaded = flagLoaded1_2_load_reg_819;
    end else if (((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_flagLoaded = flagLoaded0_3_load_reg_794;
    end else begin
        grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_flagLoaded = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state12) & (((icmp_ln882_reg_772 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)))) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln882_reg_772 == 1'd1) & (scale_up_flag_read_reg_682 == 1'd1)))) begin
        grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_row = op2_assign_reg_766;
    end else if ((((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_row = zext_ln882_reg_799;
    end else begin
        grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_row = 'bx;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        prev_cols_blk_n = prev_cols_empty_n;
    end else begin
        prev_cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((scale_in_empty_n == 1'b0) | (scale_up_flag_empty_n == 1'b0) | (cols_empty_n == 1'b0) | (rows_empty_n == 1'b0) | (prev_cols_empty_n == 1'b0) | (prev_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        prev_cols_read = 1'b1;
    end else begin
        prev_cols_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        prev_rows_blk_n = prev_rows_empty_n;
    end else begin
        prev_rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((scale_in_empty_n == 1'b0) | (scale_up_flag_empty_n == 1'b0) | (cols_empty_n == 1'b0) | (rows_empty_n == 1'b0) | (prev_cols_empty_n == 1'b0) | (prev_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        prev_rows_read = 1'b1;
    end else begin
        prev_rows_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rows_blk_n = rows_empty_n;
    end else begin
        rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((scale_in_empty_n == 1'b0) | (scale_up_flag_empty_n == 1'b0) | (cols_empty_n == 1'b0) | (rows_empty_n == 1'b0) | (prev_cols_empty_n == 1'b0) | (prev_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rows_read = 1'b1;
    end else begin
        rows_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        scale_in_blk_n = scale_in_empty_n;
    end else begin
        scale_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((scale_in_empty_n == 1'b0) | (scale_up_flag_empty_n == 1'b0) | (cols_empty_n == 1'b0) | (rows_empty_n == 1'b0) | (prev_cols_empty_n == 1'b0) | (prev_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        scale_in_read = 1'b1;
    end else begin
        scale_in_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        scale_up_flag_blk_n = scale_up_flag_empty_n;
    end else begin
        scale_up_flag_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((scale_in_empty_n == 1'b0) | (scale_up_flag_empty_n == 1'b0) | (cols_empty_n == 1'b0) | (rows_empty_n == 1'b0) | (prev_cols_empty_n == 1'b0) | (prev_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        scale_up_flag_read = 1'b1;
    end else begin
        scale_up_flag_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln318_reg_752 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        strmFlowV_scaled_blk_n = strmFlowV_scaled_full_n;
    end else begin
        strmFlowV_scaled_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln318_reg_752 == 1'd0) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        strmFlowV_scaled_din = strmFlowV_split_dout;
    end else if ((((1'b1 == ap_CS_fsm_state12) & (((icmp_ln882_reg_772 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)))) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln882_reg_772 == 1'd1) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        strmFlowV_scaled_din = grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_strmFlowU_scaled17_din;
    end else begin
        strmFlowV_scaled_din = grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_strmFlowU_scaled17_din;
    end
end

always @ (*) begin
    if (((icmp_ln318_reg_752 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        strmFlowV_scaled_write = 1'b1;
    end else if ((((1'b1 == ap_CS_fsm_state12) & (((icmp_ln882_reg_772 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)))) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state12) & (icmp_ln882_reg_772 == 1'd1) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        strmFlowV_scaled_write = grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_strmFlowU_scaled17_write;
    end else begin
        strmFlowV_scaled_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln318_reg_752 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        strmFlowV_split_blk_n = strmFlowV_split_empty_n;
    end else begin
        strmFlowV_split_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln318_reg_752 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        strmFlowV_split_read = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state9) | ((flag_reg_216 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((flag_reg_216 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        strmFlowV_split_read = grp_load_data_1920_16_10_45_22_17_1_s_fu_278_strmFlowU_split15_read;
    end else begin
        strmFlowV_split_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((scale_in_empty_n == 1'b0) | (scale_up_flag_empty_n == 1'b0) | (cols_empty_n == 1'b0) | (rows_empty_n == 1'b0) | (prev_cols_empty_n == 1'b0) | (prev_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln882_5_fu_584_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (scale_up_flag_read_reg_682 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((icmp_ln882_5_fu_584_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3) & (scale_up_flag_read_reg_682 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln314_fu_589_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln318_fu_600_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln318_fu_600_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & ((icmp_ln882_6_fu_636_p2 == 1'd0) | (icmp_ln882_reg_772 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b0 == ap_block_state12_on_subcall_done) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F2_fu_386_p2 = (12'd1075 - zext_ln455_fu_346_p1);

assign add_i_i52_i_i_fu_641_p2 = (empty_158_reg_228 + 16'd1);

assign add_ln581_fu_398_p2 = ($signed(12'd4080) + $signed(F2_fu_386_p2));

assign add_ln695_4_fu_605_p2 = (empty_157_reg_205 + 16'd1);

assign add_ln695_fu_594_p2 = (empty_reg_194 + 16'd1);

assign and_ln581_fu_513_p2 = (xor_ln582_fu_507_p2 & icmp_ln581_reg_704);

assign and_ln582_fu_491_p2 = (xor_ln571_fu_486_p2 & icmp_ln582_reg_721);

assign and_ln585_2_fu_538_p2 = (xor_ln585_fu_532_p2 & and_ln581_fu_513_p2);

assign and_ln585_fu_518_p2 = (icmp_ln585_fu_429_p2 & and_ln581_fu_513_p2);

assign and_ln603_fu_563_p2 = (xor_ln581_fu_557_p2 & icmp_ln603_fu_435_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln318_reg_752 == 1'd0) & (strmFlowV_scaled_full_n == 1'b0)) | ((icmp_ln318_reg_752 == 1'd0) & (strmFlowV_split_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln318_reg_752 == 1'd0) & (strmFlowV_scaled_full_n == 1'b0)) | ((icmp_ln318_reg_752 == 1'd0) & (strmFlowV_split_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln318_reg_752 == 1'd0) & (strmFlowV_scaled_full_n == 1'b0)) | ((icmp_ln318_reg_752 == 1'd0) & (strmFlowV_split_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_state1 = ((scale_in_empty_n == 1'b0) | (scale_up_flag_empty_n == 1'b0) | (cols_empty_n == 1'b0) | (rows_empty_n == 1'b0) | (prev_cols_empty_n == 1'b0) | (prev_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state11_on_subcall_done = (((flag_reg_216 == 1'd1) & (grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_done == 1'b0)) | ((flag_reg_216 == 1'd1) & (grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_done == 1'b0)) | ((flag_reg_216 == 1'd0) & (grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_done == 1'b0)) | ((flag_reg_216 == 1'd0) & (grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_done == 1'b0)));
end

always @ (*) begin
    ap_block_state12_on_subcall_done = (((ap_predicate_op157_call_state12 == 1'b1) & (grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_done == 1'b0)) | ((ap_predicate_op155_call_state12 == 1'b1) & (grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_done == 1'b0)));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter1 = (((icmp_ln318_reg_752 == 1'd0) & (strmFlowV_scaled_full_n == 1'b0)) | ((icmp_ln318_reg_752 == 1'd0) & (strmFlowV_split_empty_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_mux_flag_phi_fu_220_p4 = flag_reg_216;

always @ (*) begin
    ap_predicate_op155_call_state12 = (((icmp_ln882_reg_772 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)) | ((flag_reg_216 == 1'd0) & (scale_up_flag_read_reg_682 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op157_call_state12 = ((flag_reg_216 == 1'd1) & (icmp_ln882_reg_772 == 1'd1) & (scale_up_flag_read_reg_682 == 1'd1));
end

assign ashr_ln586_fu_449_p2 = $signed(select_ln570_reg_692) >>> zext_ln586_fu_445_p1;

assign bitcast_ln702_fu_458_p1 = scale_in_read_reg_686;

assign exp_tmp_V_fu_336_p4 = {{ireg_fu_320_p1[62:52]}};

assign grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_start = grp_load_data_1920_16_10_45_22_17_1_s_fu_278_ap_start_reg;

assign grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_start = grp_process_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_s_fu_262_ap_start_reg;

assign icmp_ln314_fu_589_p2 = ((empty_reg_194 == rows_read_reg_668) ? 1'b1 : 1'b0);

assign icmp_ln318_fu_600_p2 = ((empty_157_reg_205 == cols_read_reg_676) ? 1'b1 : 1'b0);

assign icmp_ln571_fu_380_p2 = ((trunc_ln555_fu_324_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln581_fu_392_p2 = (($signed(F2_fu_386_p2) > $signed(12'd16)) ? 1'b1 : 1'b0);

assign icmp_ln582_fu_410_p2 = ((F2_fu_386_p2 == 12'd16) ? 1'b1 : 1'b0);

assign icmp_ln585_fu_429_p2 = ((sh_amt_fu_420_p3 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln603_fu_435_p2 = ((sh_amt_fu_420_p3 < 12'd17) ? 1'b1 : 1'b0);

assign icmp_ln882_5_fu_584_p2 = ((rows_read_reg_668 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln882_6_fu_636_p2 = (($signed(zext_ln882_fu_631_p1) < $signed(op2_assign_reg_766)) ? 1'b1 : 1'b0);

assign icmp_ln882_fu_620_p2 = (($signed(op2_assign_fu_614_p2) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign ireg_fu_320_p1 = grp_fu_294_p1;

assign man_V_2_fu_366_p2 = (54'd0 - zext_ln569_fu_362_p1);

assign op2_assign_fu_614_p2 = ($signed(outRows_cast_i_i_fu_611_p1) + $signed(17'd131071));

assign or_ln581_fu_552_p2 = (or_ln582_fu_503_p2 | icmp_ln581_reg_704);

assign or_ln582_fu_503_p2 = (icmp_ln582_reg_721 | icmp_ln571_reg_697);

assign outRows_cast_i_i_fu_611_p1 = rows_read_reg_668;

assign p_Result_2_fu_354_p3 = {{1'd1}, {trunc_ln565_fu_350_p1}};

assign p_Result_s_fu_328_p3 = ireg_fu_320_p1[32'd63];

assign scaleI_V_fu_577_p3 = ((icmp_ln571_reg_697[0:0] === 1'b1) ? 17'd0 : select_ln603_fu_569_p3);

assign select_ln570_fu_372_p3 = ((p_Result_s_fu_328_p3[0:0] === 1'b1) ? man_V_2_fu_366_p2 : zext_ln569_fu_362_p1);

assign select_ln582_fu_496_p3 = ((and_ln582_fu_491_p2[0:0] === 1'b1) ? trunc_ln583_reg_727 : 17'd0);

assign select_ln585_2_fu_544_p3 = ((and_ln585_2_fu_538_p2[0:0] === 1'b1) ? select_ln588_fu_469_p3 : select_ln585_fu_524_p3);

assign select_ln585_fu_524_p3 = ((and_ln585_fu_518_p2[0:0] === 1'b1) ? trunc_ln586_2_fu_454_p1 : select_ln582_fu_496_p3);

assign select_ln588_fu_469_p3 = ((tmp_fu_461_p3[0:0] === 1'b1) ? 17'd131071 : 17'd0);

assign select_ln603_fu_569_p3 = ((and_ln603_fu_563_p2[0:0] === 1'b1) ? shl_ln604_fu_481_p2 : select_ln585_2_fu_544_p3);

assign sext_ln581_fu_425_p1 = sh_amt_fu_420_p3;

assign sext_ln581cast_fu_477_p1 = sext_ln581_fu_425_p1[16:0];

assign sh_amt_fu_420_p3 = ((icmp_ln581_reg_704[0:0] === 1'b1) ? add_ln581_reg_711 : sub_ln581_reg_716);

assign shl_ln604_fu_481_p2 = trunc_ln583_reg_727 << sext_ln581cast_fu_477_p1;

assign sub_ln581_fu_404_p2 = (12'd16 - F2_fu_386_p2);

assign tmp_fu_461_p3 = bitcast_ln702_fu_458_p1[32'd31];

assign trunc_ln555_fu_324_p1 = ireg_fu_320_p1[62:0];

assign trunc_ln565_fu_350_p1 = ireg_fu_320_p1[51:0];

assign trunc_ln583_fu_416_p1 = select_ln570_fu_372_p3[16:0];

assign trunc_ln586_2_fu_454_p1 = ashr_ln586_fu_449_p2[16:0];

assign trunc_ln586_fu_441_p1 = sh_amt_fu_420_p3[5:0];

assign xor_ln571_fu_486_p2 = (icmp_ln571_reg_697 ^ 1'd1);

assign xor_ln581_fu_557_p2 = (or_ln581_fu_552_p2 ^ 1'd1);

assign xor_ln582_fu_507_p2 = (or_ln582_fu_503_p2 ^ 1'd1);

assign xor_ln585_fu_532_p2 = (icmp_ln585_fu_429_p2 ^ 1'd1);

assign zext_ln455_fu_346_p1 = exp_tmp_V_fu_336_p4;

assign zext_ln569_fu_362_p1 = p_Result_2_fu_354_p3;

assign zext_ln586_fu_445_p1 = trunc_ln586_fu_441_p1;

assign zext_ln882_fu_631_p1 = empty_158_reg_228;

always @ (posedge ap_clk) begin
    zext_ln882_reg_799[16] <= 1'b0;
end

endmodule //pyr_dense_optical_flow_accel_scale_up_unsigned_short_1080_unsigned_short_1920_16_10_45_22_48_16_17_1_false_s
