-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pyr_down_accel_Block_split1_proc30 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    pyr_h : IN STD_LOGIC_VECTOR (31 downto 0);
    pyr_w : IN STD_LOGIC_VECTOR (31 downto 0);
    pyr_out_h : IN STD_LOGIC_VECTOR (31 downto 0);
    pyr_out_w : IN STD_LOGIC_VECTOR (31 downto 0);
    inImgPyr1 : IN STD_LOGIC_VECTOR (63 downto 0);
    outImgPyr1 : IN STD_LOGIC_VECTOR (63 downto 0);
    inImgPyr2 : IN STD_LOGIC_VECTOR (63 downto 0);
    outImgPyr2 : IN STD_LOGIC_VECTOR (63 downto 0);
    pyr1_in_mat_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    pyr1_in_mat_rows_out_full_n : IN STD_LOGIC;
    pyr1_in_mat_rows_out_write : OUT STD_LOGIC;
    pyr1_in_mat_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    pyr1_in_mat_cols_out_full_n : IN STD_LOGIC;
    pyr1_in_mat_cols_out_write : OUT STD_LOGIC;
    pyr1_out_mat_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    pyr1_out_mat_rows_out_full_n : IN STD_LOGIC;
    pyr1_out_mat_rows_out_write : OUT STD_LOGIC;
    pyr1_out_mat_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    pyr1_out_mat_cols_out_full_n : IN STD_LOGIC;
    pyr1_out_mat_cols_out_write : OUT STD_LOGIC;
    pyr2_in_mat_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    pyr2_in_mat_rows_out_full_n : IN STD_LOGIC;
    pyr2_in_mat_rows_out_write : OUT STD_LOGIC;
    pyr2_in_mat_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    pyr2_in_mat_cols_out_full_n : IN STD_LOGIC;
    pyr2_in_mat_cols_out_write : OUT STD_LOGIC;
    pyr2_out_mat_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    pyr2_out_mat_rows_out_full_n : IN STD_LOGIC;
    pyr2_out_mat_rows_out_write : OUT STD_LOGIC;
    pyr2_out_mat_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    pyr2_out_mat_cols_out_full_n : IN STD_LOGIC;
    pyr2_out_mat_cols_out_write : OUT STD_LOGIC;
    inImgPyr1_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    inImgPyr1_out_full_n : IN STD_LOGIC;
    inImgPyr1_out_write : OUT STD_LOGIC;
    outImgPyr1_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    outImgPyr1_out_full_n : IN STD_LOGIC;
    outImgPyr1_out_write : OUT STD_LOGIC;
    inImgPyr2_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    inImgPyr2_out_full_n : IN STD_LOGIC;
    inImgPyr2_out_write : OUT STD_LOGIC;
    outImgPyr2_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    outImgPyr2_out_full_n : IN STD_LOGIC;
    outImgPyr2_out_write : OUT STD_LOGIC );
end;


architecture behav of pyr_down_accel_Block_split1_proc30 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal pyr1_in_mat_rows_out_blk_n : STD_LOGIC;
    signal pyr1_in_mat_cols_out_blk_n : STD_LOGIC;
    signal pyr1_out_mat_rows_out_blk_n : STD_LOGIC;
    signal pyr1_out_mat_cols_out_blk_n : STD_LOGIC;
    signal pyr2_in_mat_rows_out_blk_n : STD_LOGIC;
    signal pyr2_in_mat_cols_out_blk_n : STD_LOGIC;
    signal pyr2_out_mat_rows_out_blk_n : STD_LOGIC;
    signal pyr2_out_mat_cols_out_blk_n : STD_LOGIC;
    signal inImgPyr1_out_blk_n : STD_LOGIC;
    signal outImgPyr1_out_blk_n : STD_LOGIC;
    signal inImgPyr2_out_blk_n : STD_LOGIC;
    signal outImgPyr2_out_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
                ap_block_state1 <= ((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        if ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    inImgPyr1_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, inImgPyr1_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            inImgPyr1_out_blk_n <= inImgPyr1_out_full_n;
        else 
            inImgPyr1_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    inImgPyr1_out_din <= inImgPyr1;

    inImgPyr1_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        if ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            inImgPyr1_out_write <= ap_const_logic_1;
        else 
            inImgPyr1_out_write <= ap_const_logic_0;
        end if; 
    end process;


    inImgPyr2_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, inImgPyr2_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            inImgPyr2_out_blk_n <= inImgPyr2_out_full_n;
        else 
            inImgPyr2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    inImgPyr2_out_din <= inImgPyr2;

    inImgPyr2_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        if ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            inImgPyr2_out_write <= ap_const_logic_1;
        else 
            inImgPyr2_out_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        if ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    outImgPyr1_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, outImgPyr1_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            outImgPyr1_out_blk_n <= outImgPyr1_out_full_n;
        else 
            outImgPyr1_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    outImgPyr1_out_din <= outImgPyr1;

    outImgPyr1_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        if ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            outImgPyr1_out_write <= ap_const_logic_1;
        else 
            outImgPyr1_out_write <= ap_const_logic_0;
        end if; 
    end process;


    outImgPyr2_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, outImgPyr2_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            outImgPyr2_out_blk_n <= outImgPyr2_out_full_n;
        else 
            outImgPyr2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    outImgPyr2_out_din <= outImgPyr2;

    outImgPyr2_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        if ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            outImgPyr2_out_write <= ap_const_logic_1;
        else 
            outImgPyr2_out_write <= ap_const_logic_0;
        end if; 
    end process;


    pyr1_in_mat_cols_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_cols_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr1_in_mat_cols_out_blk_n <= pyr1_in_mat_cols_out_full_n;
        else 
            pyr1_in_mat_cols_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pyr1_in_mat_cols_out_din <= pyr_w;

    pyr1_in_mat_cols_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        if ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr1_in_mat_cols_out_write <= ap_const_logic_1;
        else 
            pyr1_in_mat_cols_out_write <= ap_const_logic_0;
        end if; 
    end process;


    pyr1_in_mat_rows_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr1_in_mat_rows_out_blk_n <= pyr1_in_mat_rows_out_full_n;
        else 
            pyr1_in_mat_rows_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pyr1_in_mat_rows_out_din <= pyr_h;

    pyr1_in_mat_rows_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        if ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr1_in_mat_rows_out_write <= ap_const_logic_1;
        else 
            pyr1_in_mat_rows_out_write <= ap_const_logic_0;
        end if; 
    end process;


    pyr1_out_mat_cols_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_out_mat_cols_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr1_out_mat_cols_out_blk_n <= pyr1_out_mat_cols_out_full_n;
        else 
            pyr1_out_mat_cols_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pyr1_out_mat_cols_out_din <= pyr_out_w;

    pyr1_out_mat_cols_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        if ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr1_out_mat_cols_out_write <= ap_const_logic_1;
        else 
            pyr1_out_mat_cols_out_write <= ap_const_logic_0;
        end if; 
    end process;


    pyr1_out_mat_rows_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_out_mat_rows_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr1_out_mat_rows_out_blk_n <= pyr1_out_mat_rows_out_full_n;
        else 
            pyr1_out_mat_rows_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pyr1_out_mat_rows_out_din <= pyr_out_h;

    pyr1_out_mat_rows_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        if ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr1_out_mat_rows_out_write <= ap_const_logic_1;
        else 
            pyr1_out_mat_rows_out_write <= ap_const_logic_0;
        end if; 
    end process;


    pyr2_in_mat_cols_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr2_in_mat_cols_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr2_in_mat_cols_out_blk_n <= pyr2_in_mat_cols_out_full_n;
        else 
            pyr2_in_mat_cols_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pyr2_in_mat_cols_out_din <= pyr_w;

    pyr2_in_mat_cols_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        if ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr2_in_mat_cols_out_write <= ap_const_logic_1;
        else 
            pyr2_in_mat_cols_out_write <= ap_const_logic_0;
        end if; 
    end process;


    pyr2_in_mat_rows_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr2_in_mat_rows_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr2_in_mat_rows_out_blk_n <= pyr2_in_mat_rows_out_full_n;
        else 
            pyr2_in_mat_rows_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pyr2_in_mat_rows_out_din <= pyr_h;

    pyr2_in_mat_rows_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        if ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr2_in_mat_rows_out_write <= ap_const_logic_1;
        else 
            pyr2_in_mat_rows_out_write <= ap_const_logic_0;
        end if; 
    end process;


    pyr2_out_mat_cols_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr2_out_mat_cols_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr2_out_mat_cols_out_blk_n <= pyr2_out_mat_cols_out_full_n;
        else 
            pyr2_out_mat_cols_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pyr2_out_mat_cols_out_din <= pyr_out_w;

    pyr2_out_mat_cols_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        if ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr2_out_mat_cols_out_write <= ap_const_logic_1;
        else 
            pyr2_out_mat_cols_out_write <= ap_const_logic_0;
        end if; 
    end process;


    pyr2_out_mat_rows_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr2_out_mat_rows_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr2_out_mat_rows_out_blk_n <= pyr2_out_mat_rows_out_full_n;
        else 
            pyr2_out_mat_rows_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pyr2_out_mat_rows_out_din <= pyr_out_h;

    pyr2_out_mat_rows_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, pyr1_in_mat_rows_out_full_n, pyr1_in_mat_cols_out_full_n, pyr1_out_mat_rows_out_full_n, pyr1_out_mat_cols_out_full_n, pyr2_in_mat_rows_out_full_n, pyr2_in_mat_cols_out_full_n, pyr2_out_mat_rows_out_full_n, pyr2_out_mat_cols_out_full_n, inImgPyr1_out_full_n, outImgPyr1_out_full_n, inImgPyr2_out_full_n, outImgPyr2_out_full_n)
    begin
        if ((not(((outImgPyr2_out_full_n = ap_const_logic_0) or (inImgPyr2_out_full_n = ap_const_logic_0) or (outImgPyr1_out_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (inImgPyr1_out_full_n = ap_const_logic_0) or (pyr2_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr2_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr2_in_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_out_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_out_mat_rows_out_full_n = ap_const_logic_0) or (pyr1_in_mat_cols_out_full_n = ap_const_logic_0) or (pyr1_in_mat_rows_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            pyr2_out_mat_rows_out_write <= ap_const_logic_1;
        else 
            pyr2_out_mat_rows_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
